<a href="https://colab.research.google.com/github/angel-myr/prep-python/blob/main/numpy_ez.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
# Numpy Parte III
---

In [245]:
import numpy as np
import pandas as pd
import time

ruta_sales = 'supermarket_sales.xlsx'
df_sales = pd.read_excel(ruta_sales)

df_sales

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,13:08:00,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29:00,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,13:23:00,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27,20:33:00,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2019-02-08,10:37:00,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,2019-01-29,13:46:00,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,2019-03-02,17:16:00,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2019-02-09,13:22:00,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2019-02-22,15:33:00,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2019-02-18,13:28:00,Cash,618.38,4.761905,30.9190,6.6

In [246]:
df_sales['Quantity'].mean()

np.float64(5.51)

In [247]:
np.round(df_sales['Quantity'].mean())

np.float64(6.0)

In [248]:
np.round(np.min(df_sales['Total'])), np.round(np.max(df_sales['Total']))

(np.float64(11.0), np.float64(1043.0))

## Arrays en Numpy

In [249]:
ingreso_bruto = np.array(df_sales['gross income'])
ingreso_bruto

array([26.1415,  3.82  , 16.2155, 23.288 , 30.2085, 29.8865, 20.652 ,
       36.78  ,  3.626 ,  8.226 ,  2.896 ,  5.102 , 11.7375, 21.595 ,
       35.69  , 28.116 , 24.1255, 21.783 ,  8.2005,  4.03  , 21.51  ,
       13.197 ,  3.32  ,  8.64  , 13.2945, 21.036 ,  1.676 ,  8.767 ,
       22.09  , 11.2005, 23.5325, 35.1315, 33.512 ,  9.658 , 19.884 ,
        3.406 , 15.655 , 27.396 , 21.968 , 12.048 ,  4.336 ,  5.611 ,
       20.736 , 39.48  ,  1.537 , 18.792 , 25.5105,  9.0045,  5.679 ,
       41.315 , 31.99  , 11.1475,  3.574 ,  0.7715,  1.616 , 34.392 ,
        4.434 , 35.84  , 36.175 ,  9.183 ,  3.711 , 16.719 , 24.7815,
        7.905 , 15.148 ,  7.935 ,  3.347 , 29.283 , 39.385 ,  0.9165,
       44.74  , 31.06  ,  7.278 , 22.773 , 33.6015, 20.825 , 22.068 ,
        9.0045, 39.155 ,  5.095 , 29.757 , 14.502 ,  7.7   , 16.072 ,
       12.2275, 29.071 , 19.13  , 17.283 ,  2.1235, 23.097 ,  9.476 ,
       22.43  ,  7.693 , 28.962 ,  4.4875,  4.858 , 43.935 ,  3.735 ,
        7.9125, 24.81  ,  2.4355, 35.3475, 10.3815, 17.478 , 10.6225,
       44.335 ,  8.214 , 18.639 , 15.291 , 40.985 ,  1.649 , 14.7315,
       25.494 , 26.1315, 36.3555,  4.053 ,  5.485 ,  2.568 ,  5.48  ,
        5.344 , 39.824 , 19.992 , 44.982 , 25.564 , 22.588 , 32.7915,
        8.0625, 14.2785, 27.416 , 40.626 , 13.867 , 27.639 ,  6.968 ,
       26.235 , 24.39  , 13.533 ,  6.5775, 10.326 , 25.955 , 29.    ,
       44.9   , 45.25  , 34.3   ,  1.5205, 23.385 , 13.878 , 15.07  ,
       13.228 , 28.744 , 12.984 , 18.308 , 12.096 , 37.458 ,  4.944 ,
       32.388 , 23.0725,  3.6085, 12.57  , 43.749 , 28.017 , 17.272 ,
        3.1845, 16.0265,  7.64  , 19.95  , 17.028 , 47.79  , 49.49  ,
       15.384 , 24.332 , 17.5025, 20.0125,  8.34  , 15.867 ,  7.916 ,
       15.228 ,  8.868 ,  7.8785, 22.164 , 13.02  , 22.491 , 15.388 ,
        7.75  , 13.724 ,  4.319 ,  2.712 , 37.796 ,  9.294 ,  3.7035,
       13.962 , 11.556 ,  7.352 , 39.51  ,  5.11  ,  8.1775,  3.7145,
        4.37  ,  1.2645,  8.3   , 17.8475,  5.745 , 11.498 , 21.4935,
       12.95  ,  4.4425, 10.3635, 29.9925, 14.265 ,  4.5555, 44.8785,
       11.8035, 41.967 , 23.09  ,  6.963 , 10.3635,  0.914 ,  6.1925,
       14.196 , 37.948 ,  8.601 , 13.605 , 21.728 ,  2.9525,  0.627 ,
        4.325 ,  8.716 , 31.2165,  7.412 , 27.21  , 25.368 ,  8.137 ,
        1.5885, 37.8405, 14.764 , 25.97  ,  9.314 ,  4.3525, 11.055 ,
        3.305 ,  4.4845, 11.223 ,  5.977 ,  9.32  , 12.53  , 37.548 ,
       19.036 , 12.21  ,  4.485 , 15.544 , 25.571 , 20.9475, 17.595 ,
        1.439 ,  4.75  , 23.56  ,  6.524 ,  3.3175,  7.773 ,  6.45  ,
       13.188 , 33.777 ,  3.29  ,  7.66  , 11.12  ,  2.7225, 34.44  ,
        7.094 , 37.3   , 14.148 , 17.77  , 16.8575,  2.112 ,  9.693 ,
        1.203 , 29.913 , 16.7895, 10.91  , 19.084 , 35.495 , 22.01  ,
       27.984 ,  1.85  ,  0.767 , 29.949 ,  9.534 , 16.67  ,  3.743 ,
       10.6875, 16.9785, 33.208 , 20.15  ,  9.7475,  3.124 ,  3.636 ,
        9.055 , 12.98  ,  5.768 , 23.514 , 12.002 ,  4.4305,  9.982 ,
        1.9505,  2.4305, 10.238 ,  5.984 , 25.27  , 14.0805, 35.516 ,
        3.972 ,  8.191 , 23.979 ,  6.933 ,  3.5575,  6.9975, 39.065 ,
        9.937 ,  3.162 , 18.6975, 10.3845,  8.814 , 10.3185,  1.971 ,
        4.578 , 15.4425,  6.456 , 19.548 , 24.945 , 18.852 , 10.226 ,
        7.272 ,  9.909 ,  4.935 , 19.255 ,  2.348 ,  3.675 ,  7.1125,
       34.38  , 17.385 ,  7.1475, 19.269 ,  7.2135, 19.5895, 26.915 ,
       24.2575,  6.6975, 35.0685,  3.5975, 35.7   ,  9.107 ,  6.75  ,
       49.65  , 18.0915, 19.1555, 12.15  ,  1.512 , 17.828 , 18.775 ,
       47.72  ,  4.125 ,  3.7485, 32.384 , 37.788 ,  9.979 , 21.966 ,
        8.248 , 16.336 , 23.094 , 13.188 ,  7.18  ,  9.675 ,  9.191 ,
        6.096 , 21.033 , 12.624 , 16.7725, 24.175 , 15.921 , 33.4215,
       19.396 ,  4.73  , 16.466 ,  2.661 , 24.9225, 14.978 , 10.235 ,
        3.791 , 14.031 , 16.16  , 24.3315,  6.377 , 12.072 , 18.975 ,
        3.841 , 26.13  ,  3.987 , 19.375 , 13.5675,  6.1155, 12.318 ,
        8.658 , 11.829 ,  9.244 ,  0.699 ,  9.9375, 34.2265, 13.452 ,
        3.4475, 13.742 , 11.306 ,  5.955 , 17.105 ,  2.187 ,  5.2425,
        3.876 , 20.372 ,  4.8055,  9.076 ,  4.0755,  5.722 ,  8.827 ,
        5.79  , 12.6075, 48.605 , 10.168 ,  0.814 , 18.2745, 18.6095,
        3.1305, 16.8175, 45.325 ,  6.908 ,  4.327 ,  7.038 , 33.439 ,
        2.372 , 44.658 , 16.586 , 10.197 ,  3.408 , 16.344 ,  4.36  ,
       35.372 , 40.1445,  0.639 ,  6.685 ,  0.9575, 13.83  ,  6.861 ,
        1.3535,  1.956 , 22.413 ,  6.603 , 15.9025,  1.25  ,  4.154 ,
        7.39  , 34.83  , 39.695 , 23.285 ,  1.7945, 10.13  , 36.525 ,
       14.79  ,  1.131 , 12.835 , 27.275 , 13.0025, 11.106 ,  1.079 ,
        4.942 , 25.131 ,  8.01  , 21.565 , 29.028 , 16.11  ,  9.777 ,
        8.315 , 16.814 , 17.185 ,  1.93  , 26.388 , 16.4   ,  9.285 ,
       30.19  , 18.49  ,  9.898 , 20.545 ,  7.43  ,  1.148 , 34.956 ,
        3.47  ,  9.83  , 10.128 ,  6.06  ,  9.989 , 30.368 ,  6.322 ,
       27.072 ,  4.9065, 20.608 ,  3.6985,  1.595 ,  6.94  ,  9.331 ,
        4.4225,  9.672 ,  7.275 , 25.215 , 15.3225,  4.785 , 31.759 ,
       10.7275, 18.998 , 34.8425, 20.4365,  2.5735, 13.715 ,  9.8475,
        3.473 , 17.98  ,  6.8565, 24.951 , 11.232 ,  6.287 , 24.513 ,
       22.8525,  7.842 ,  5.986 , 27.18  , 44.1405,  7.629 , 34.672 ,
       11.475 ,  7.3395,  7.08  ,  5.8345,  3.698 ,  4.897 , 14.61  ,
       26.244 ,  4.602 ,  3.794 ,  4.036 ,  5.631 ,  3.56  ,  7.762 ,
       14.71  , 27.4275, 12.885 , 19.818 ,  8.5905, 24.4395, 26.208 ,
        6.663 ,  6.762 ,  5.622 ,  7.204 , 49.26  , 12.498 , 10.863 ,
        9.711 , 44.6   , 16.968 , 22.353 ,  9.925 , 40.605 , 24.665 ,
       29.583 , 27.951 , 25.893 , 20.51  , 13.335 ,  3.5455,  7.239 ,
       21.4775, 28.4585, 12.06  ,  6.354 , 12.854 ,  6.951 ,  4.083 ,
       15.536 ,  9.298 ,  3.616 ,  9.459 , 10.342 ,  7.851 , 10.765 ,
       29.805 ,  3.655 , 13.959 ,  8.484 ,  2.279 , 11.28  , 14.52  ,
        2.223 ,  7.83  , 20.997 ,  9.2125,  7.032 ,  4.154 ,  3.2495,
       38.78  , 16.353 , 18.1615,  6.35  , 18.7775,  9.958 ,  1.5305,
        5.789 ,  1.448 , 44.5365, 13.983 ,  4.0465, 33.725 , 17.424 ,
       21.78  , 21.9775, 29.559 , 13.038 , 10.752 ,  4.5805, 33.1065,
       41.625 ,  4.5675,  7.888 ,  6.087 , 41.29  ,  7.995 ,  0.6045,
       32.095 , 11.7465,  8.377 , 14.955 , 11.9865, 33.235 , 10.1325,
        2.31  ,  4.4075,  7.863 , 14.8185, 35.42  ,  5.567 , 29.008 ,
        3.0125,  8.712 , 21.063 ,  1.6815,  1.549 , 12.37  , 18.915 ,
       16.743 , 36.39  , 16.794 , 12.036 ,  2.3535,  4.9845, 13.2225,
        6.9825,  2.7725,  6.4455,  5.999 , 17.625 , 43.55  ,  9.88  ,
        9.726 ,  8.661 ,  3.594 , 14.313 ,  4.062 , 28.02  ,  9.34  ,
       11.0115, 13.456 , 22.74  ,  8.377 , 22.428 , 14.694 , 29.475 ,
       14.55  ,  1.974 ,  1.7405, 14.796 ,  2.148 ,  6.924 ,  4.91  ,
        6.483 , 31.78  ,  7.288 , 10.065 , 31.5855, 19.264 , 24.315 ,
       25.683 , 23.67  , 21.8425,  5.408 , 12.438 , 31.311 , 48.75  ,
       24.164 ,  4.848 ,  9.885 , 36.2115, 39.7755, 25.1195,  8.6   ,
        3.449 ,  6.248 ,  3.855 , 24.186 , 15.106 , 34.9335,  6.2325,
       39.48  ,  8.92  , 25.011 ,  1.791 ,  6.807 ,  5.244 ,  8.946 ,
       40.7835,  6.618 , 12.8695,  4.668 , 11.4   ,  8.3355, 34.87  ,
       19.452 , 18.263 ,  4.464 ,  8.4   ,  0.985 , 26.558 ,  2.686 ,
       40.975 , 28.42  , 29.38  , 36.624 , 42.282 , 19.4635,  4.2415,
        7.163 ,  3.769 , 12.668 ,  1.921 , 32.615 ,  2.6325,  5.5305,
       28.4305,  4.464 ,  6.82  ,  8.71  , 18.32  , 12.7305, 38.916 ,
       14.296 , 28.956 ,  9.425 , 11.078 , 38.6   , 36.065 , 25.552 ,
        2.6725, 11.1   , 38.184 , 11.409 ,  4.107 , 19.128 ,  3.429 ,
       19.108 , 30.0545, 23.7965,  2.621 ,  6.565 ,  7.215 , 22.8585,
        4.669 ,  6.3125, 39.5415,  8.72  , 18.952 ,  1.531 , 17.604 ,
        2.54  , 26.103 , 28.756 ,  2.7475,  9.0705, 20.6185,  2.3205,
       13.71  , 48.685 , 32.41  ,  4.661 ,  2.718 ,  3.0435, 12.245 ,
        4.639 , 21.6725,  6.903 , 12.08  , 23.5865, 22.032 , 34.0155,
       15.494 ,  9.318 , 10.046 ,  0.8875, 31.09  ,  4.3   , 20.13  ,
       16.2425,  4.7575, 19.448 , 21.284 , 15.904 , 13.552 , 19.232 ,
       11.79  , 10.578 ,  4.768 ,  0.5085, 10.3065, 21.028 ,  4.402 ,
       32.4495,  6.192 , 32.475 , 37.11  ,  4.224 , 12.514 ,  4.74  ,
        4.565 , 14.2555,  2.619 ,  9.635 , 13.389 , 27.935 ,  8.766 ,
        7.791 ,  3.015 ,  3.947 ,  1.487 ,  1.066 , 14.067 ,  3.663 ,
        1.119 , 32.796 , 29.73  ,  3.705 ,  9.848 , 18.6165, 26.395 ,
       23.9875, 16.4295,  8.448 ,  5.662 , 17.277 , 21.4335,  4.3135,
        1.276 ,  5.076 , 17.8745, 11.9385,  5.0715, 36.212 ,  6.282 ,
        3.6465, 12.918 ,  8.687 ,  2.825 , 10.715 , 26.718 ,  4.658 ,
       26.104 ,  2.6175,  1.9875, 36.008 ,  4.84  , 16.605 ,  4.072 ,
       15.995 , 10.326 ,  8.334 , 15.953 ,  4.395 , 36.735 ,  4.876 ,
       38.46  , 20.915 , 23.164 , 23.1225,  7.095 , 15.135 , 39.664 ,
       21.259 , 14.181 , 29.96  , 15.768 , 20.178 ,  9.194 ,  6.9325,
        4.0355,  5.832 , 15.676 , 42.305 , 20.72  ,  7.954 , 24.505 ,
        4.3725, 11.226 , 37.248 , 20.536 , 14.94  , 10.647 ,  2.1425,
       18.934 , 10.3455,  3.939 , 16.1055,  4.911 ,  1.273 , 29.099 ,
       10.566 ,  2.756 ,  4.4155, 17.829 , 39.7125,  2.531 , 29.976 ,
        8.335 , 37.22  , 22.428 , 18.945 , 12.858 , 27.6115, 22.37  ,
       13.8135, 17.187 , 13.304 , 44.919 , 22.84  , 12.6975,  3.528 ,
       32.858 ,  8.425 ,  2.689 ,  8.9525, 10.572 ,  5.9865,  3.285 ,
       12.57  ,  4.208 , 19.773 , 14.8995, 22.7205, 13.806 ,  7.9   ,
       44.397 ,  4.599 ,  2.089 ,  0.775 , 14.523 ,  3.333 ,  3.827 ,
       14.985 , 12.1515,  2.37  ,  8.6225, 42.315 , 12.9185, 30.478 ,
       12.012 ,  8.613 ,  4.992 , 14.932 ,  7.98  ,  1.2725,  3.3885,
       11.918 , 11.63  , 43.866 , 34.986 , 33.7295, 15.9275,  1.476 ,
       24.8   , 41.17  , 30.148 , 14.14  , 38.3   ,  5.803 ,  8.745 ,
        3.0475,  2.0175, 48.69  ,  1.592 ,  3.291 , 30.919 ])

In [250]:
init_recorrido = time.time()
ingreso_bruto ** 2
end_recorrido = time.time()
print(f'Tiempo de recorrido: {end_recorrido - init_recorrido}')

Tiempo de recorrido: 0.0005998611450195312

## Tipos de Arrays

In [251]:
len(ingreso_bruto)

1000

In [252]:
ingreso_bruto.shape

(1000,)

In [253]:
# Array bidimensional
ingreso_rebruto = np.column_stack((ingreso_bruto, ingreso_bruto ** 2))
ingreso_rebruto

array([[ 26.1415, 683.378 ],
       [  3.82  ,  14.5924],
       [ 16.2155, 262.9424],
       ...,
       [  1.592 ,   2.5345],
       [  3.291 ,  10.8307],
       [ 30.919 , 955.9846]])

In [254]:
len(ingreso_rebruto)

1000

In [255]:
ingreso_rebruto.shape

(1000, 2)

## Manipulación de Arrays

In [256]:
# Concatenación
precio_unitario = np.array(df_sales['Unit price'])
cantidad = np.array(df_sales['Quantity'])
impuesto = np.array(df_sales['Tax 5%'])
total = np.array(df_sales['Total'])

np.concatenate([precio_unitario, cantidad, impuesto])

array([74.69 , 15.28 , 46.33 , ...,  1.592,  3.291, 30.919])

In [257]:
np.concatenate([precio_unitario, cantidad, impuesto], axis = 0)

array([74.69 , 15.28 , 46.33 , ...,  1.592,  3.291, 30.919])

In [258]:
# Alterar tamaño
valor_concatenado = np.concatenate([precio_unitario, cantidad, impuesto], axis = 0)
valor_concatenado.shape

(3000,)

In [259]:
valor_reformado = valor_concatenado.reshape(1000, 3)
valor_reformado

array([[74.69  , 15.28  , 46.33  ],
       [58.22  , 86.31  , 85.39  ],
       [68.84  , 73.56  , 36.26  ],
       ...,
       [38.3   ,  5.803 ,  8.745 ],
       [ 3.0475,  2.0175, 48.69  ],
       [ 1.592 ,  3.291 , 30.919 ]])

In [260]:
valor_reformado = valor_concatenado.reshape(3, 1000)
valor_reformado

array([[74.69  , 15.28  , 46.33  , ..., 31.84  , 65.82  , 88.34  ],
       [ 7.    ,  5.    ,  7.    , ...,  1.    ,  1.    ,  7.    ],
       [26.1415,  3.82  , 16.2155, ...,  1.592 ,  3.291 , 30.919 ]])

In [261]:
# Trasponer
valor_reformado = valor_reformado.T
valor_reformado

array([[74.69  ,  7.    , 26.1415],
       [15.28  ,  5.    ,  3.82  ],
       [46.33  ,  7.    , 16.2155],
       ...,
       [31.84  ,  1.    ,  1.592 ],
       [65.82  ,  1.    ,  3.291 ],
       [88.34  ,  7.    , 30.919 ]])

In [262]:
# Operaciones
ganancia_bruta = precio_unitario * cantidad
ganancia_bruta

array([522.83,  76.4 , 324.31, 465.76, 604.17, 597.73, 413.04, 735.6 ,
        72.52, 164.52,  57.92, 102.04, 234.75, 431.9 , 713.8 , 562.32,
       482.51, 435.66, 164.01,  80.6 , 430.2 , 263.94,  66.4 , 172.8 ,
       265.89, 420.72,  33.52, 175.34, 441.8 , 224.01, 470.65, 702.63,
       670.24, 193.16, 397.68,  68.12, 313.1 , 547.92, 439.36, 240.96,
        86.72, 112.22, 414.72, 789.6 ,  30.74, 375.84, 510.21, 180.09,
       113.58, 826.3 , 639.8 , 222.95,  71.48,  15.43,  32.32, 687.84,
        88.68, 716.8 , 723.5 , 183.66,  74.22, 334.38, 495.63, 158.1 ,
       302.96, 158.7 ,  66.94, 585.66, 787.7 ,  18.33, 894.8 , 621.2 ,
       145.56, 455.46, 672.03, 416.5 , 441.36, 180.09, 783.1 , 101.9 ,
       595.14, 290.04, 154.  , 321.44, 244.55, 581.42, 382.6 , 345.66,
        42.47, 461.94, 189.52, 448.6 , 153.86, 579.24,  89.75,  97.16,
       878.7 ,  74.7 , 158.25, 496.2 ,  48.71, 706.95, 207.63, 349.56,
       212.45, 886.7 , 164.28, 372.78, 305.82, 819.7 ,  32.98, 294.63,
       509.88, 522.63, 727.11,  81.06, 109.7 ,  51.36, 109.6 , 106.88,
       796.48, 399.84, 899.64, 511.28, 451.76, 655.83, 161.25, 285.57,
       548.32, 812.52, 277.34, 552.78, 139.36, 524.7 , 487.8 , 270.66,
       131.55, 206.52, 519.1 , 580.  , 898.  , 905.  , 686.  ,  30.41,
       467.7 , 277.56, 301.4 , 264.56, 574.88, 259.68, 366.16, 241.92,
       749.16,  98.88, 647.76, 461.45,  72.17, 251.4 , 874.98, 560.34,
       345.44,  63.69, 320.53, 152.8 , 399.  , 340.56, 955.8 , 989.8 ,
       307.68, 486.64, 350.05, 400.25, 166.8 , 317.34, 158.32, 304.56,
       177.36, 157.57, 443.28, 260.4 , 449.82, 307.76, 155.  , 274.48,
        86.38,  54.24, 755.92, 185.88,  74.07, 279.24, 231.12, 147.04,
       790.2 , 102.2 , 163.55,  74.29,  87.4 ,  25.29, 166.  , 356.95,
       114.9 , 229.96, 429.87, 259.  ,  88.85, 207.27, 599.85, 285.3 ,
        91.11, 897.57, 236.07, 839.34, 461.8 , 139.26, 207.27,  18.28,
       123.85, 283.92, 758.96, 172.02, 272.1 , 434.56,  59.05,  12.54,
        86.5 , 174.32, 624.33, 148.24, 544.2 , 507.36, 162.74,  31.77,
       756.81, 295.28, 519.4 , 186.28,  87.05, 221.1 ,  66.1 ,  89.69,
       224.46, 119.54, 186.4 , 250.6 , 750.96, 380.72, 244.2 ,  89.7 ,
       310.88, 511.42, 418.95, 351.9 ,  28.78,  95.  , 471.2 , 130.48,
        66.35, 155.46, 129.  , 263.76, 675.54,  65.8 , 153.2 , 222.4 ,
        54.45, 688.8 , 141.88, 746.  , 282.96, 355.4 , 337.15,  42.24,
       193.86,  24.06, 598.26, 335.79, 218.2 , 381.68, 709.9 , 440.2 ,
       559.68,  37.  ,  15.34, 598.98, 190.68, 333.4 ,  74.86, 213.75,
       339.57, 664.16, 403.  , 194.95,  62.48,  72.72, 181.1 , 259.6 ,
       115.36, 470.28, 240.04,  88.61, 199.64,  39.01,  48.61, 204.76,
       119.68, 505.4 , 281.61, 710.32,  79.44, 163.82, 479.58, 138.66,
        71.15, 139.95, 781.3 , 198.74,  63.24, 373.95, 207.69, 176.28,
       206.37,  39.42,  91.56, 308.85, 129.12, 390.96, 498.9 , 377.04,
       204.52, 145.44, 198.18,  98.7 , 385.1 ,  46.96,  73.5 , 142.25,
       687.6 , 347.7 , 142.95, 385.38, 144.27, 391.79, 538.3 , 485.15,
       133.95, 701.37,  71.95, 714.  , 182.14, 135.  , 993.  , 361.83,
       383.11, 243.  ,  30.24, 356.56, 375.5 , 954.4 ,  82.5 ,  74.97,
       647.68, 755.76, 199.58, 439.32, 164.96, 326.72, 461.88, 263.76,
       143.6 , 193.5 , 183.82, 121.92, 420.66, 252.48, 335.45, 483.5 ,
       318.42, 668.43, 387.92,  94.6 , 329.32,  53.22, 498.45, 299.56,
       204.7 ,  75.82, 280.62, 323.2 , 486.63, 127.54, 241.44, 379.5 ,
        76.82, 522.6 ,  79.74, 387.5 , 271.35, 122.31, 246.36, 173.16,
       236.58, 184.88,  13.98, 198.75, 684.53, 269.04,  68.95, 274.84,
       226.12, 119.1 , 342.1 ,  43.74, 104.85,  77.52, 407.44,  96.11,
       181.52,  81.51, 114.44, 176.54, 115.8 , 252.15, 972.1 , 203.36,
        16.28, 365.49, 372.19,  62.61, 336.35, 906.5 , 138.16,  86.54,
       140.76, 668.78,  47.44, 893.16, 331.72, 203.94,  68.16, 326.88,
        87.2 , 707.44, 802.89,  12.78, 133.7 ,  19.15, 276.6 , 137.22,
        27.07,  39.12, 448.26, 132.06, 318.05,  25.  ,  83.08, 147.8 ,
       696.6 , 793.9 , 465.7 ,  35.89, 202.6 , 730.5 , 295.8 ,  22.62,
       256.7 , 545.5 , 260.05, 222.12,  21.58,  98.84, 502.62, 160.2 ,
       431.3 , 580.56, 322.2 , 195.54, 166.3 , 336.28, 343.7 ,  38.6 ,
       527.76, 328.  , 185.7 , 603.8 , 369.8 , 197.96, 410.9 , 148.6 ,
        22.96, 699.12,  69.4 , 196.6 , 202.56, 121.2 , 199.78, 607.36,
       126.44, 541.44,  98.13, 412.16,  73.97,  31.9 , 138.8 , 186.62,
        88.45, 193.44, 145.5 , 504.3 , 306.45,  95.7 , 635.18, 214.55,
       379.96, 696.85, 408.73,  51.47, 274.3 , 196.95,  69.46, 359.6 ,
       137.13, 499.02, 224.64, 125.74, 490.26, 457.05, 156.84, 119.72,
       543.6 , 882.81, 152.58, 693.44, 229.5 , 146.79, 141.6 , 116.69,
        73.96,  97.94, 292.2 , 524.88,  92.04,  75.88,  80.72, 112.62,
        71.2 , 155.24, 294.2 , 548.55, 257.7 , 396.36, 171.81, 488.79,
       524.16, 133.26, 135.24, 112.44, 144.08, 985.2 , 249.96, 217.26,
       194.22, 892.  , 339.36, 447.06, 198.5 , 812.1 , 493.3 , 591.66,
       559.02, 517.86, 410.2 , 266.7 ,  70.91, 144.78, 429.55, 569.17,
       241.2 , 127.08, 257.08, 139.02,  81.66, 310.72, 185.96,  72.32,
       189.18, 206.84, 157.02, 215.3 , 596.1 ,  73.1 , 279.18, 169.68,
        45.58, 225.6 , 290.4 ,  44.46, 156.6 , 419.94, 184.25, 140.64,
        83.08,  64.99, 775.6 , 327.06, 363.23, 127.  , 375.55, 199.16,
        30.61, 115.78,  28.96, 890.73, 279.66,  80.93, 674.5 , 348.48,
       435.6 , 439.55, 591.18, 260.76, 215.04,  91.61, 662.13, 832.5 ,
        91.35, 157.76, 121.74, 825.8 , 159.9 ,  12.09, 641.9 , 234.93,
       167.54, 299.1 , 239.73, 664.7 , 202.65,  46.2 ,  88.15, 157.26,
       296.37, 708.4 , 111.34, 580.16,  60.25, 174.24, 421.26,  33.63,
        30.98, 247.4 , 378.3 , 334.86, 727.8 , 335.88, 240.72,  47.07,
        99.69, 264.45, 139.65,  55.45, 128.91, 119.98, 352.5 , 871.  ,
       197.6 , 194.52, 173.22,  71.88, 286.26,  81.24, 560.4 , 186.8 ,
       220.23, 269.12, 454.8 , 167.54, 448.56, 293.88, 589.5 , 291.  ,
        39.48,  34.81, 295.92,  42.96, 138.48,  98.2 , 129.66, 635.6 ,
       145.76, 201.3 , 631.71, 385.28, 486.3 , 513.66, 473.4 , 436.85,
       108.16, 248.76, 626.22, 975.  , 483.28,  96.96, 197.7 , 724.23,
       795.51, 502.39, 172.  ,  68.98, 124.96,  77.1 , 483.72, 302.12,
       698.67, 124.65, 789.6 , 178.4 , 500.22,  35.82, 136.14, 104.88,
       178.92, 815.67, 132.36, 257.39,  93.36, 228.  , 166.71, 697.4 ,
       389.04, 365.26,  89.28, 168.  ,  19.7 , 531.16,  53.72, 819.5 ,
       568.4 , 587.6 , 732.48, 845.64, 389.27,  84.83, 143.26,  75.38,
       253.36,  38.42, 652.3 ,  52.65, 110.61, 568.61,  89.28, 136.4 ,
       174.2 , 366.4 , 254.61, 778.32, 285.92, 579.12, 188.5 , 221.56,
       772.  , 721.3 , 511.04,  53.45, 222.  , 763.68, 228.18,  82.14,
       382.56,  68.58, 382.16, 601.09, 475.93,  52.42, 131.3 , 144.3 ,
       457.17,  93.38, 126.25, 790.83, 174.4 , 379.04,  30.62, 352.08,
        50.8 , 522.06, 575.12,  54.95, 181.41, 412.37,  46.41, 274.2 ,
       973.7 , 648.2 ,  93.22,  54.36,  60.87, 244.9 ,  92.78, 433.45,
       138.06, 241.6 , 471.73, 440.64, 680.31, 309.88, 186.36, 200.92,
        17.75, 621.8 ,  86.  , 402.6 , 324.85,  95.15, 388.96, 425.68,
       318.08, 271.04, 384.64, 235.8 , 211.56,  95.36,  10.17, 206.13,
       420.56,  88.04, 648.99, 123.84, 649.5 , 742.2 ,  84.48, 250.28,
        94.8 ,  91.3 , 285.11,  52.38, 192.7 , 267.78, 558.7 , 175.32,
       155.82,  60.3 ,  78.94,  29.74,  21.32, 281.34,  73.26,  22.38,
       655.92, 594.6 ,  74.1 , 196.96, 372.33, 527.9 , 479.75, 328.59,
       168.96, 113.24, 345.54, 428.67,  86.27,  25.52, 101.52, 357.49,
       238.77, 101.43, 724.24, 125.64,  72.93, 258.36, 173.74,  56.5 ,
       214.3 , 534.36,  93.16, 522.08,  52.35,  39.75, 720.16,  96.8 ,
       332.1 ,  81.44, 319.9 , 206.52, 166.68, 319.06,  87.9 , 734.7 ,
        97.52, 769.2 , 418.3 , 463.28, 462.45, 141.9 , 302.7 , 793.28,
       425.18, 283.62, 599.2 , 315.36, 403.56, 183.88, 138.65,  80.71,
       116.64, 313.52, 846.1 , 414.4 , 159.08, 490.1 ,  87.45, 224.52,
       744.96, 410.72, 298.8 , 212.94,  42.85, 378.68, 206.91,  78.78,
       322.11,  98.22,  25.46, 581.98, 211.32,  55.12,  88.31, 356.58,
       794.25,  50.62, 599.52, 166.7 , 744.4 , 448.56, 378.9 , 257.16,
       552.23, 447.4 , 276.27, 343.74, 266.08, 898.38, 456.8 , 253.95,
        70.56, 657.16, 168.5 ,  53.78, 179.05, 211.44, 119.73,  65.7 ,
       251.4 ,  84.16, 395.46, 297.99, 454.41, 276.12, 158.  , 887.94,
        91.98,  41.78,  15.5 , 290.46,  66.66,  76.54, 299.7 , 243.03,
        47.4 , 172.45, 846.3 , 258.37, 609.56, 240.24, 172.26,  99.84,
       298.64, 159.6 ,  25.45,  67.77, 238.36, 232.6 , 877.32, 699.72,
       674.59, 318.55,  29.52, 496.  , 823.4 , 602.96, 282.8 , 766.  ,
       116.06, 174.9 ,  60.95,  40.35, 973.8 ,  31.84,  65.82, 618.38])

## Indexación y Segmentación de Arrays

In [263]:
rating = np.array(df_sales['Rating'])
rating[500:505]

array([5.4, 9.1, 9. , 6.3, 9.5])

In [264]:
# Hasta el unidimensinal 2, y hasta el elemento 3
valor_reformado[:2, :3]

array([[74.69  ,  7.    , 26.1415],
       [15.28  ,  5.    ,  3.82  ]])

In [265]:
# Información
(rating[250:750] > 5.99)

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True, False, False, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False,  True,  True, False,  True, False,
        True,  True, False, False,  True,  True, False, False, False,
        True, False,  True, False, False,  True, False,  True, False,
       False, False, False,  True, False,  True,  True, False,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False,  True, False,  True, False,  True,  True,  True, False,
        True, False,  True,  True,  True,  True,  True,  True, False,
        True, False,  True,  True, False, False,  True,  True,  True,
        True,  True,  True, False,  True, False,  True, False,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False,  True,  True,  True,  True,  True,
        True, False,  True,  True, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False, False, False,  True, False,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True, False,  True,  True, False,  True, False, False,  True,
        True, False, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
       False, False,  True,  True, False, False,  True, False,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True, False, False, False,  True,
        True,  True,  True, False, False,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False,  True,
        True, False, False,  True,  True, False,  True,  True,  True,
       False,  True,  True, False,  True, False,  True, False,  True,
        True,  True,  True,  True, False, False,  True, False, False,
        True,  True,  True, False, False,  True,  True,  True, False,
        True,  True,  True, False,  True, False, False, False,  True,
        True,  True,  True,  True, False,  True, False, False,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
       False,  True,  True, False, False,  True,  True, False,  True,
        True,  True,  True,  True, False, False, False, False, False,
        True, False, False,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True, False, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True,  True, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True, False, False,  True,  True])

## Forma y Estructura de Arrays

In [266]:
valor_reformado

array([[74.69  ,  7.    , 26.1415],
       [15.28  ,  5.    ,  3.82  ],
       [46.33  ,  7.    , 16.2155],
       ...,
       [31.84  ,  1.    ,  1.592 ],
       [65.82  ,  1.    ,  3.291 ],
       [88.34  ,  7.    , 30.919 ]])

In [267]:
valor_reformado.transpose()

array([[74.69  , 15.28  , 46.33  , ..., 31.84  , 65.82  , 88.34  ],
       [ 7.    ,  5.    ,  7.    , ...,  1.    ,  1.    ,  7.    ],
       [26.1415,  3.82  , 16.2155, ...,  1.592 ,  3.291 , 30.919 ]])

In [268]:
valor_reformado.transpose().flatten()

array([74.69 , 15.28 , 46.33 , ...,  1.592,  3.291, 30.919])

## Operaciones avanzadas y Funciones Universales

In [269]:
np.multiply(precio_unitario, cantidad)

array([522.83,  76.4 , 324.31, 465.76, 604.17, 597.73, 413.04, 735.6 ,
        72.52, 164.52,  57.92, 102.04, 234.75, 431.9 , 713.8 , 562.32,
       482.51, 435.66, 164.01,  80.6 , 430.2 , 263.94,  66.4 , 172.8 ,
       265.89, 420.72,  33.52, 175.34, 441.8 , 224.01, 470.65, 702.63,
       670.24, 193.16, 397.68,  68.12, 313.1 , 547.92, 439.36, 240.96,
        86.72, 112.22, 414.72, 789.6 ,  30.74, 375.84, 510.21, 180.09,
       113.58, 826.3 , 639.8 , 222.95,  71.48,  15.43,  32.32, 687.84,
        88.68, 716.8 , 723.5 , 183.66,  74.22, 334.38, 495.63, 158.1 ,
       302.96, 158.7 ,  66.94, 585.66, 787.7 ,  18.33, 894.8 , 621.2 ,
       145.56, 455.46, 672.03, 416.5 , 441.36, 180.09, 783.1 , 101.9 ,
       595.14, 290.04, 154.  , 321.44, 244.55, 581.42, 382.6 , 345.66,
        42.47, 461.94, 189.52, 448.6 , 153.86, 579.24,  89.75,  97.16,
       878.7 ,  74.7 , 158.25, 496.2 ,  48.71, 706.95, 207.63, 349.56,
       212.45, 886.7 , 164.28, 372.78, 305.82, 819.7 ,  32.98, 294.63,
       509.88, 522.63, 727.11,  81.06, 109.7 ,  51.36, 109.6 , 106.88,
       796.48, 399.84, 899.64, 511.28, 451.76, 655.83, 161.25, 285.57,
       548.32, 812.52, 277.34, 552.78, 139.36, 524.7 , 487.8 , 270.66,
       131.55, 206.52, 519.1 , 580.  , 898.  , 905.  , 686.  ,  30.41,
       467.7 , 277.56, 301.4 , 264.56, 574.88, 259.68, 366.16, 241.92,
       749.16,  98.88, 647.76, 461.45,  72.17, 251.4 , 874.98, 560.34,
       345.44,  63.69, 320.53, 152.8 , 399.  , 340.56, 955.8 , 989.8 ,
       307.68, 486.64, 350.05, 400.25, 166.8 , 317.34, 158.32, 304.56,
       177.36, 157.57, 443.28, 260.4 , 449.82, 307.76, 155.  , 274.48,
        86.38,  54.24, 755.92, 185.88,  74.07, 279.24, 231.12, 147.04,
       790.2 , 102.2 , 163.55,  74.29,  87.4 ,  25.29, 166.  , 356.95,
       114.9 , 229.96, 429.87, 259.  ,  88.85, 207.27, 599.85, 285.3 ,
        91.11, 897.57, 236.07, 839.34, 461.8 , 139.26, 207.27,  18.28,
       123.85, 283.92, 758.96, 172.02, 272.1 , 434.56,  59.05,  12.54,
        86.5 , 174.32, 624.33, 148.24, 544.2 , 507.36, 162.74,  31.77,
       756.81, 295.28, 519.4 , 186.28,  87.05, 221.1 ,  66.1 ,  89.69,
       224.46, 119.54, 186.4 , 250.6 , 750.96, 380.72, 244.2 ,  89.7 ,
       310.88, 511.42, 418.95, 351.9 ,  28.78,  95.  , 471.2 , 130.48,
        66.35, 155.46, 129.  , 263.76, 675.54,  65.8 , 153.2 , 222.4 ,
        54.45, 688.8 , 141.88, 746.  , 282.96, 355.4 , 337.15,  42.24,
       193.86,  24.06, 598.26, 335.79, 218.2 , 381.68, 709.9 , 440.2 ,
       559.68,  37.  ,  15.34, 598.98, 190.68, 333.4 ,  74.86, 213.75,
       339.57, 664.16, 403.  , 194.95,  62.48,  72.72, 181.1 , 259.6 ,
       115.36, 470.28, 240.04,  88.61, 199.64,  39.01,  48.61, 204.76,
       119.68, 505.4 , 281.61, 710.32,  79.44, 163.82, 479.58, 138.66,
        71.15, 139.95, 781.3 , 198.74,  63.24, 373.95, 207.69, 176.28,
       206.37,  39.42,  91.56, 308.85, 129.12, 390.96, 498.9 , 377.04,
       204.52, 145.44, 198.18,  98.7 , 385.1 ,  46.96,  73.5 , 142.25,
       687.6 , 347.7 , 142.95, 385.38, 144.27, 391.79, 538.3 , 485.15,
       133.95, 701.37,  71.95, 714.  , 182.14, 135.  , 993.  , 361.83,
       383.11, 243.  ,  30.24, 356.56, 375.5 , 954.4 ,  82.5 ,  74.97,
       647.68, 755.76, 199.58, 439.32, 164.96, 326.72, 461.88, 263.76,
       143.6 , 193.5 , 183.82, 121.92, 420.66, 252.48, 335.45, 483.5 ,
       318.42, 668.43, 387.92,  94.6 , 329.32,  53.22, 498.45, 299.56,
       204.7 ,  75.82, 280.62, 323.2 , 486.63, 127.54, 241.44, 379.5 ,
        76.82, 522.6 ,  79.74, 387.5 , 271.35, 122.31, 246.36, 173.16,
       236.58, 184.88,  13.98, 198.75, 684.53, 269.04,  68.95, 274.84,
       226.12, 119.1 , 342.1 ,  43.74, 104.85,  77.52, 407.44,  96.11,
       181.52,  81.51, 114.44, 176.54, 115.8 , 252.15, 972.1 , 203.36,
        16.28, 365.49, 372.19,  62.61, 336.35, 906.5 , 138.16,  86.54,
       140.76, 668.78,  47.44, 893.16, 331.72, 203.94,  68.16, 326.88,
        87.2 , 707.44, 802.89,  12.78, 133.7 ,  19.15, 276.6 , 137.22,
        27.07,  39.12, 448.26, 132.06, 318.05,  25.  ,  83.08, 147.8 ,
       696.6 , 793.9 , 465.7 ,  35.89, 202.6 , 730.5 , 295.8 ,  22.62,
       256.7 , 545.5 , 260.05, 222.12,  21.58,  98.84, 502.62, 160.2 ,
       431.3 , 580.56, 322.2 , 195.54, 166.3 , 336.28, 343.7 ,  38.6 ,
       527.76, 328.  , 185.7 , 603.8 , 369.8 , 197.96, 410.9 , 148.6 ,
        22.96, 699.12,  69.4 , 196.6 , 202.56, 121.2 , 199.78, 607.36,
       126.44, 541.44,  98.13, 412.16,  73.97,  31.9 , 138.8 , 186.62,
        88.45, 193.44, 145.5 , 504.3 , 306.45,  95.7 , 635.18, 214.55,
       379.96, 696.85, 408.73,  51.47, 274.3 , 196.95,  69.46, 359.6 ,
       137.13, 499.02, 224.64, 125.74, 490.26, 457.05, 156.84, 119.72,
       543.6 , 882.81, 152.58, 693.44, 229.5 , 146.79, 141.6 , 116.69,
        73.96,  97.94, 292.2 , 524.88,  92.04,  75.88,  80.72, 112.62,
        71.2 , 155.24, 294.2 , 548.55, 257.7 , 396.36, 171.81, 488.79,
       524.16, 133.26, 135.24, 112.44, 144.08, 985.2 , 249.96, 217.26,
       194.22, 892.  , 339.36, 447.06, 198.5 , 812.1 , 493.3 , 591.66,
       559.02, 517.86, 410.2 , 266.7 ,  70.91, 144.78, 429.55, 569.17,
       241.2 , 127.08, 257.08, 139.02,  81.66, 310.72, 185.96,  72.32,
       189.18, 206.84, 157.02, 215.3 , 596.1 ,  73.1 , 279.18, 169.68,
        45.58, 225.6 , 290.4 ,  44.46, 156.6 , 419.94, 184.25, 140.64,
        83.08,  64.99, 775.6 , 327.06, 363.23, 127.  , 375.55, 199.16,
        30.61, 115.78,  28.96, 890.73, 279.66,  80.93, 674.5 , 348.48,
       435.6 , 439.55, 591.18, 260.76, 215.04,  91.61, 662.13, 832.5 ,
        91.35, 157.76, 121.74, 825.8 , 159.9 ,  12.09, 641.9 , 234.93,
       167.54, 299.1 , 239.73, 664.7 , 202.65,  46.2 ,  88.15, 157.26,
       296.37, 708.4 , 111.34, 580.16,  60.25, 174.24, 421.26,  33.63,
        30.98, 247.4 , 378.3 , 334.86, 727.8 , 335.88, 240.72,  47.07,
        99.69, 264.45, 139.65,  55.45, 128.91, 119.98, 352.5 , 871.  ,
       197.6 , 194.52, 173.22,  71.88, 286.26,  81.24, 560.4 , 186.8 ,
       220.23, 269.12, 454.8 , 167.54, 448.56, 293.88, 589.5 , 291.  ,
        39.48,  34.81, 295.92,  42.96, 138.48,  98.2 , 129.66, 635.6 ,
       145.76, 201.3 , 631.71, 385.28, 486.3 , 513.66, 473.4 , 436.85,
       108.16, 248.76, 626.22, 975.  , 483.28,  96.96, 197.7 , 724.23,
       795.51, 502.39, 172.  ,  68.98, 124.96,  77.1 , 483.72, 302.12,
       698.67, 124.65, 789.6 , 178.4 , 500.22,  35.82, 136.14, 104.88,
       178.92, 815.67, 132.36, 257.39,  93.36, 228.  , 166.71, 697.4 ,
       389.04, 365.26,  89.28, 168.  ,  19.7 , 531.16,  53.72, 819.5 ,
       568.4 , 587.6 , 732.48, 845.64, 389.27,  84.83, 143.26,  75.38,
       253.36,  38.42, 652.3 ,  52.65, 110.61, 568.61,  89.28, 136.4 ,
       174.2 , 366.4 , 254.61, 778.32, 285.92, 579.12, 188.5 , 221.56,
       772.  , 721.3 , 511.04,  53.45, 222.  , 763.68, 228.18,  82.14,
       382.56,  68.58, 382.16, 601.09, 475.93,  52.42, 131.3 , 144.3 ,
       457.17,  93.38, 126.25, 790.83, 174.4 , 379.04,  30.62, 352.08,
        50.8 , 522.06, 575.12,  54.95, 181.41, 412.37,  46.41, 274.2 ,
       973.7 , 648.2 ,  93.22,  54.36,  60.87, 244.9 ,  92.78, 433.45,
       138.06, 241.6 , 471.73, 440.64, 680.31, 309.88, 186.36, 200.92,
        17.75, 621.8 ,  86.  , 402.6 , 324.85,  95.15, 388.96, 425.68,
       318.08, 271.04, 384.64, 235.8 , 211.56,  95.36,  10.17, 206.13,
       420.56,  88.04, 648.99, 123.84, 649.5 , 742.2 ,  84.48, 250.28,
        94.8 ,  91.3 , 285.11,  52.38, 192.7 , 267.78, 558.7 , 175.32,
       155.82,  60.3 ,  78.94,  29.74,  21.32, 281.34,  73.26,  22.38,
       655.92, 594.6 ,  74.1 , 196.96, 372.33, 527.9 , 479.75, 328.59,
       168.96, 113.24, 345.54, 428.67,  86.27,  25.52, 101.52, 357.49,
       238.77, 101.43, 724.24, 125.64,  72.93, 258.36, 173.74,  56.5 ,
       214.3 , 534.36,  93.16, 522.08,  52.35,  39.75, 720.16,  96.8 ,
       332.1 ,  81.44, 319.9 , 206.52, 166.68, 319.06,  87.9 , 734.7 ,
        97.52, 769.2 , 418.3 , 463.28, 462.45, 141.9 , 302.7 , 793.28,
       425.18, 283.62, 599.2 , 315.36, 403.56, 183.88, 138.65,  80.71,
       116.64, 313.52, 846.1 , 414.4 , 159.08, 490.1 ,  87.45, 224.52,
       744.96, 410.72, 298.8 , 212.94,  42.85, 378.68, 206.91,  78.78,
       322.11,  98.22,  25.46, 581.98, 211.32,  55.12,  88.31, 356.58,
       794.25,  50.62, 599.52, 166.7 , 744.4 , 448.56, 378.9 , 257.16,
       552.23, 447.4 , 276.27, 343.74, 266.08, 898.38, 456.8 , 253.95,
        70.56, 657.16, 168.5 ,  53.78, 179.05, 211.44, 119.73,  65.7 ,
       251.4 ,  84.16, 395.46, 297.99, 454.41, 276.12, 158.  , 887.94,
        91.98,  41.78,  15.5 , 290.46,  66.66,  76.54, 299.7 , 243.03,
        47.4 , 172.45, 846.3 , 258.37, 609.56, 240.24, 172.26,  99.84,
       298.64, 159.6 ,  25.45,  67.77, 238.36, 232.6 , 877.32, 699.72,
       674.59, 318.55,  29.52, 496.  , 823.4 , 602.96, 282.8 , 766.  ,
       116.06, 174.9 ,  60.95,  40.35, 973.8 ,  31.84,  65.82, 618.38])

In [270]:
np.add(cantidad, rating)

array([16.1, 14.6, 14.4, 16.4, 12.3, 11.1, 11.8, 18. ,  9.2,  8.9,  8.5,
       10.8, 12.1, 18.2, 15.7, 10.5, 11.6, 12.9, 11.6,  6.4,  9.8,  8.1,
        6.4, 14.9,  9. , 16.5,  7.7,  9.7, 14.6, 16.4,  9.8, 13.5, 13.1,
        7.1, 11.5,  7.8, 12. , 13.7, 15.6, 15.7,  8.9,  8.3, 11.6, 15.6,
        9.2, 13.5, 17.4, 13.1, 14.1, 17.9, 16.5, 13.5, 10.5,  7.1,  8.5,
       16.2,  7.8, 14.6, 15.4, 15.3, 13. , 13. , 19. , 18.6, 11.6, 15.8,
        8.7, 15.9, 16.4,  5.3, 19.6, 15.9,  7. , 14.7, 18.4, 15.4, 17.6,
       14.7, 16.6, 11. , 11.5,  9.4, 14.6, 12.3, 11.6, 11. , 14.9, 14.3,
        6.7, 12.1, 11.1, 18.2, 12.1, 17.6,  7.6,  8.2, 15.1, 10.1, 12.3,
       13.4,  5.1, 16.2, 13.9, 15.9, 15. , 17.3, 13.9, 13.4, 13.2, 19.2,
        6.6, 10.8, 15.4, 13.3, 18.5, 10.1, 10.3,  6.2, 16. ,  6.1, 13.2,
       13.5, 13.2, 12.6, 15.3, 11.5, 14. , 14.9, 16.5, 16.2, 14.5, 14.3,
       11.4, 14.8, 11.3,  9.2, 13.8, 15.8, 18.2, 17.2, 15.4, 18.1, 19.1,
        9.4, 14. , 15.5, 19.2,  9.6, 14.2, 12.9,  8.8, 14.3, 16.4, 15.9,
       17.3, 14. ,  7.1, 14.7, 15. , 16. , 16.3,  7. , 14. ,  8.5, 15.9,
       13.6, 14.8, 18.7, 12.5, 15.5, 10.5, 14.4, 14.3, 15.8, 16.7, 17.8,
       17.6, 11.8, 10.4, 12.9, 12.7, 15.7, 18. , 13.7, 13.7, 11. , 15.5,
       11. , 10.9,  9.9, 10.2,  6.6, 18.2,  9.7, 14.9,  6. ,  6.9,  7.1,
       12.2, 10.5, 12.8, 10.6, 16.8, 18.7, 10.4, 16.9, 18.7, 17.8,  8.1,
       15.5, 14.9, 17.8,  9.9,  7.4, 13.5,  9.3, 13.5,  8.5, 16.7, 10.9,
       12.1, 12.4, 14.4,  9.2,  8.2, 11.7, 13. , 13.7, 11.3, 15.4,  8.5,
       11.7, 17. , 10.7, 16.5,  6.1,  9.9, 13.6,  9.3,  5.9, 14.6,  7.8,
        8. ,  8.2, 16.3, 13.7,  7.8, 11.8, 12.8, 11.2, 15.4, 18.4,  9.2,
        9.2, 16.9, 13. , 10.7, 14.7, 10.5, 10.9, 15.2,  9.6,  9.7, 14.2,
        8.9, 15.7, 10.9, 19.5,  8.4, 17. , 11.3, 11.7, 17.8,  7.1, 13.9,
       13.2, 17.1, 10.4, 15.7, 19.6, 14.4,  8.9,  7.5, 14.5, 13.1, 12.6,
        7.9, 18.5, 12.2, 11.2, 17. , 13. ,  5.7,  9.1, 15.9, 12.5, 10.4,
       11.8,  8.5,  8.7,  8.7,  5.7,  5.4,  8.7, 16.6, 11.3, 16.6, 12.1,
        7.7,  9.8, 11.5, 11.7,  9.4, 14. , 14.4,  7.2, 10.3,  9.9, 15.1,
       12.4, 14.5,  9.4, 15.8, 11.7, 15.4, 10.4, 10.4, 12.6,  8. , 11.6,
       15.8, 12.1, 10.5,  9.9, 13.5, 14.1, 16.5, 11.2, 12.5, 17.9, 10.8,
       15.9, 14.7, 14.3,  9.2, 16.6,  8.3, 12.7, 12.1, 14.8, 16.6, 12.5,
       15.5, 13.8,  9.4, 11.8, 19.3, 15.2,  9.5,  6.6, 15.4, 17.1, 10. ,
       13.2, 11.1, 13.1, 14.6, 10. , 15.4, 16.8, 16.9,  6.9, 11.2, 14.9,
       14.1, 12. , 18.6, 15.7, 13.4,  8. , 11.5,  6.2, 14.9,  8.2, 14.9,
        6.8, 12. , 20. , 18.5, 13.6, 11.1, 19.7,  8.2, 16.2,  8.3,  9.3,
        9.6, 14.8, 14.3, 17. , 15.4, 10.2, 10.8, 14.6, 11.9, 12. , 12.8,
        8.1,  9.5, 10.4, 15.1,  8.9, 12.8,  9.6, 17.2,  8.8, 12.7, 10.2,
       10.3, 15.2, 10.5, 12.8, 18.7, 14.7,  6. , 16. , 15.9, 11. , 11.9,
       17.3,  8.9,  7.7, 12.4, 16.6,  7.8, 18. , 13.6, 13.7, 11. , 14.5,
       13.1, 12.3, 15.5, 10.5, 16.7, 10.5, 18.9,  9.5,  6.3, 10.6, 12.7,
       13.6,  9.8,  6.5,  8.7, 11.9, 13.5, 16.2, 17.6,  8.9,  9.5, 18.7,
       10.1,  7.4, 14.1, 17.1, 14.7, 10.5,  8.2,  9.4, 11.4, 13.7, 15.5,
       12.6, 11.6,  9.3,  9.2,  8.4, 16.7,  7.7, 16.4, 16.2, 10. , 16. ,
       17. , 10.6, 17.3, 12.3,  5.3, 18.8, 10.2, 17.2, 16.7, 18.4,  9.1,
       13.5, 10.5, 12.2,  9.9, 17.6,  6.4, 10.1, 11. ,  8.3, 10.5, 17.8,
        9.7, 13.7, 12. , 11.1, 13.2, 11.1, 16.3, 14.6, 15.2,  9.5, 14.8,
       13.7, 11.7,  9.3, 10.7, 13.3, 11.9,  7. , 14. , 12.1, 13. ,  8.7,
       16.1, 18.3, 13. , 15.2, 18.2, 17.4, 11.2, 14.4,  6. ,  7.9,  8.9,
       11.1, 12.1,  8.1,  9. , 11.5, 10.2,  8.9, 18.9, 15. ,  9.2, 13.3,
        9.5, 17.9, 18.7, 14.6, 13.9, 10.7, 11.5, 14.5, 11.6, 11.2, 16.3,
       14.4, 13.7, 11. , 11. , 16.3, 19.4, 16.7, 12.5, 11.1, 12.6, 18.6,
       15.3, 10.1, 13.6, 13.3,  9.8, 10.2, 11.7, 10.1, 10.3, 12.4, 10. ,
       13.5, 10. , 13.8, 12.2, 12.7, 15.3,  9.4, 10.3, 16.4, 10.8,  7.8,
        8.3, 11.7, 12.5, 14.3, 14.2, 11.6,  7.4,  5.5, 16.9, 13.8, 11.5,
       12.6, 12.2, 10.4,  6.2, 10.9,  7.2, 15.7, 10.2, 10. , 14.2, 13.2,
       12.9,  9.4, 10. , 14.5, 12.2, 10.8, 11.9, 14.4,  7.8, 11.1, 10.7,
       15. , 10.5,  9.2, 16.7,  8.4,  9. ,  7.7,  8. , 15. , 13. ,  7.3,
       13.5, 10.5,  9.4, 12.7,  8. , 12. , 10.5, 17.7, 13.4,  6.6,  8.3,
       17.1, 12.8, 15.9, 17.3, 14.1, 13.4,  8.8,  9. , 10.9, 10.9,  5.9,
       12.3, 14.9, 11.9, 19.9,  9.7, 11.6, 10.7, 10.4, 10.4,  6.1, 14.4,
        7.5,  7. , 17.3, 14.8,  6.6, 14.3, 10. , 18.1, 15.4,  7.5,  8. ,
       13.1,  8.6, 10.9,  8.4, 10. , 14.3,  8.1, 10.5, 15.7, 12.2, 18.8,
       16.5, 16.6, 11.6, 10.9,  8.3, 16.8, 18. , 17.6,  7.3, 15. , 18.2,
       15.3, 15.9, 11.6,  5.8, 17.1,  9.1, 15.1, 12.3, 16.2, 15. , 16.5,
       11.6, 11.5, 11.1, 10.2, 12.1, 14.1, 14.1, 10.9, 14.4, 11.4, 14.6,
        8.9, 18.9, 10.8, 16.3,  8.4,  7.8, 10.5, 15.9,  7.4, 16. , 15.1,
       19. , 14. , 18.8, 15.5,  9.8, 10.8, 11.5, 13.6,  9.6, 15.2, 10.8,
       17. , 16. ,  8.1, 13.6, 17. , 13.4, 10.4, 14.2, 12.9, 10.5, 15.6,
       12. , 15.6, 14.2, 17.9, 12.6, 10.6, 12.7, 12.8, 12.3, 11.9, 13.7,
        8.5, 15. , 12.7,  7.3,  8. , 13. , 11.2, 10.6, 11.1, 14.6, 16.3,
       11.8,  5.1, 16.8,  9.1, 16. , 13.5, 14.3,  8.6, 16.7,  5. , 13.2,
       14.9, 16.3,  8.6,  6.3,  6.5, 18.1, 10.8, 14.4, 13.9, 13.1, 13.9,
       17. , 17. ,  8.2, 10.5, 13. ,  9.6, 16. , 14.2, 15. , 11.5,  7. ,
       13. , 13. , 16.2, 17.6, 12.4, 11. , 10.7,  6.1,  6.9, 11.7, 11.5,
       10.6, 16.7, 11.5, 15.2, 14.3, 15.6, 13.5, 12.1, 10.2, 12.4,  6.8,
       10.6, 11.1, 15.8, 11. , 10.9,  7. ,  7. , 10.9,  6.9,  8.9, 10.7,
        9.6, 13. , 10.2, 10.2, 11.2, 12. , 20. , 13.8, 13.2, 14.3, 12.2,
       11.1, 14. ,  8. ,  9.8, 13.3, 14. ,  9.6, 10.3, 14.5,  6.9,  7.3,
       13.3, 14.1, 10.6, 16.2, 15.9,  9.9, 14.3,  5. ,  7.1, 12.5, 16.6,
       16. , 17.5, 19.9, 13.5,  9.6, 12. ,  7.7, 19.5, 14.8, 15.6, 12.2,
       16.1, 13.6, 14.4, 14.9, 12.2, 12. , 14.8, 12.3, 13.6, 16.5,  9.1,
        9.2, 15.1,  8. , 11.9, 18.8, 11.6,  8.2, 14.2, 10.3, 12.6, 14.8,
       15.6,  8.8, 10.1, 10.3, 10.8, 11.7,  9.3, 14.1, 13. ,  7.2, 13.6,
       12.5, 13. ,  6.2, 15.8, 16.6,  9.2, 13.1, 11.5, 15.1, 14.6, 15.8,
        8.1, 14.5, 12.4,  7.2, 11.9, 10.9, 15.6, 15.7, 10.3, 11.2, 14.3,
        7.3,  5.7, 12.9, 16.9, 12.3,  7.7, 12.7, 11.6, 11.7, 13.8, 14.4,
       13.1, 17.8, 17.4, 10.8, 11.8,  8.4,  9.7,  8.4,  7.8, 16.2, 12.3,
       12.5, 14. , 19. , 13.7, 12.5,  8.4, 10.2,  9. , 12.5, 10.9,  6.1,
        7.5, 13.8, 12.4, 16.4, 13.1, 13. , 13.5,  6.3, 14.2, 14.3, 16.4,
        9.5, 16. , 10.8, 16.6,  6.9,  7.2, 14.4,  8.7,  5.1, 13.6])

In [271]:
np.subtract(
    total,
    np.add(
        np.multiply(precio_unitario, cantidad),
        impuesto
    )
)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,
        0.,  0.,  0., -0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0., -0.,
       -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0., -0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0., -0.,
        0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0., -0.,  0.,  0.,  0., -0.,  0., -0.,  0.,  0.,  0.,
       -0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
       -0., -0.,  0., -0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,
        0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0., -0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0., -0.,
       -0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0., -0., -0.,  0., -0.,  0., -0.,  0.,  0., -0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0., -0.,
       -0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0., -0.,  0.,  0.,  0.,  0.,  0., -0.,  0., -0.,  0.,  0., -0.,
        0., -0.,  0.,  0.,  0.,  0., -0., -0., -0.,  0.,  0., -0.,  0.,
        0.,  0.,  0.,  0., -0.,  0., -0., -0.,  0.,  0.,  0., -0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0., -0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0., -0.,
        0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,
       -0., -0.,  0., -0.,  0., -0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,
        0.,  0., -0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,
        0., -0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0., -0.,  0.,  0.,  0., -0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,
        0., -0.,  0.,  0., -0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0., -0.,  0.,  0.,  0., -0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,
        0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0., -0.,  0.,  0., -0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,
        0., -0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0., -0.,
        0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0., -0.,  0.,
        0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,
        0.,  0.,  0., -0., -0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,
       -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,
       -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0., -0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
       -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,
       -0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0., -0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,
        0., -0.,  0.,  0.,  0., -0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0., -0.,  0.,  0., -0.,  0.,  0., -0.,  0.,
        0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0., -0.,  0.,  0., -0.,  0., -0.,  0.,  0.,  0., -0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
       -0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0., -0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0., -0., -0.,  0.,
        0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
       -0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0., -0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0., -0., -0.,  0.,  0.,  0.,  0., -0.,
        0., -0.,  0.,  0., -0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,
        0.,  0.,  0., -0.,  0., -0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,
        0.,  0., -0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,
        0.,  0., -0., -0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,
       -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0., -0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0., -0.,  0.,
        0.,  0.,  0.,  0.,  0., -0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,
       -0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,
        0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [272]:
np.log(total)

array([6.308 , 4.3848, 5.8305, 6.1925, 6.4526, 6.4419, 6.0723, 6.6495,
       4.3327, 5.1518, 4.1079, 4.6742, 5.5073, 6.117 , 6.6194, 6.3809,
       6.2278, 6.1257, 5.1487, 4.4383, 6.113 , 5.6245, 4.2445, 5.2009,
       5.6319, 6.0908, 3.5609, 5.2155, 6.1396, 5.4605, 6.2029, 6.6036,
       6.5564, 5.3123, 6.0344, 4.2701, 5.7953, 6.3549, 6.1341, 5.5334,
       4.5115, 4.7693, 6.0764, 6.7203, 3.4744, 5.978 , 6.2836, 5.2422,
       4.7813, 6.7657, 6.5099, 5.4557, 4.3182, 2.7851, 3.5245, 6.5823,
       4.5338, 6.6236, 6.6329, 5.2619, 4.3558, 5.8611, 6.2546, 5.112 ,
       5.7624, 5.1158, 4.2526, 6.4215, 6.7179, 2.9573, 6.8454, 6.4804,
       5.0294, 6.1701, 6.5591, 6.0807, 6.1387, 5.2422, 6.7121, 4.6728,
       6.4376, 5.7188, 5.0857, 5.8216, 5.5482, 6.4143, 5.9958, 5.8942,
       3.7976, 6.1842, 5.2933, 6.1549, 5.0848, 6.4105, 4.5458, 4.6251,
       6.8272, 4.3623, 5.113 , 6.2558, 3.9347, 6.6098, 5.3845, 5.9055,
       5.4075, 6.8363, 5.1504, 5.9698, 5.7718, 6.7577, 3.5447, 5.7345,
       6.283 , 6.3077, 6.6379, 4.444 , 4.7465, 3.9876, 4.7456, 4.7205,
       6.729 , 6.0399, 6.8508, 6.2857, 6.1619, 6.5347, 5.1317, 5.7033,
       6.3556, 6.7489, 5.674 , 6.3638, 4.9859, 6.3116, 6.2387, 5.6497,
       4.9282, 5.3792, 6.3009, 6.4118, 6.849 , 6.8567, 6.5797, 3.4636,
       6.1966, 5.6748, 5.7572, 5.6269, 6.403 , 5.6082, 5.9519, 5.5374,
       6.6677, 4.6427, 6.5223, 6.1832, 4.3278, 5.5758, 6.823 , 6.3773,
       5.8936, 4.2028, 5.8188, 5.0779, 6.0378, 5.8794, 6.9113, 6.9463,
       5.7779, 6.2363, 5.9069, 6.0409, 5.1656, 5.8088, 5.1134, 5.7677,
       5.227 , 5.1087, 6.143 , 5.611 , 6.1576, 5.7781, 5.0922, 5.6637,
       4.5075, 4.0422, 6.6767, 5.2739, 4.3538, 5.6809, 5.4917, 5.0395,
       6.7211, 4.6757, 5.1459, 4.3568, 4.5193, 3.2792, 5.1608, 5.9264,
       4.7929, 5.4867, 6.1123, 5.6056, 4.5357, 5.3828, 6.4455, 5.7023,
       4.5609, 6.8485, 5.5129, 6.7814, 6.1839, 4.9851, 5.3828, 2.9546,
       4.8679, 5.6975, 6.6807, 5.1964, 5.655 , 6.1231, 4.1272, 2.5777,
       4.5089, 5.2097, 6.4855, 5.0476, 6.3481, 6.278 , 5.1409, 3.5073,
       6.6779, 5.7367, 6.3015, 5.276 , 4.5153, 5.4474, 4.24  , 4.5451,
       5.4625, 4.8324, 5.2767, 5.5726, 6.6701, 5.9909, 5.5468, 4.5453,
       5.7882, 6.286 , 6.0865, 5.9121, 3.4085, 4.6027, 6.2041, 4.92  ,
       4.2437, 5.0952, 4.9086, 5.6238, 6.5643, 4.2354, 5.0805, 5.4533,
       4.0461, 6.5837, 5.0038, 6.6635, 5.6941, 5.922 , 5.8693, 3.7922,
       5.3159, 3.2293, 6.4428, 5.8653, 5.4342, 5.9934, 6.6139, 6.136 ,
       6.3762, 3.6597, 2.7793, 6.444 , 5.2994, 5.8581, 4.3644, 5.4136,
       5.8765, 6.5473, 6.0477, 5.3215, 4.1836, 4.3354, 5.2478, 5.6079,
       4.7968, 6.2021, 5.5296, 4.533 , 5.3453, 3.7126, 3.9326, 5.3706,
       4.8336, 6.2741, 5.6893, 6.6145, 4.4238, 5.1476, 6.2217, 4.9808,
       4.3136, 4.9901, 6.7097, 5.3408, 4.1957, 5.9729, 5.3848, 5.2209,
       5.3785, 3.7231, 4.5658, 5.7816, 4.9095, 6.0174, 6.2612, 5.9811,
       5.3695, 5.0286, 5.338 , 4.6409, 6.0023, 3.8981, 4.3461, 5.0064,
       6.582 , 5.9001, 5.0113, 6.003 , 5.0205, 6.0195, 6.3372, 6.2332,
       4.9463, 6.6018, 4.3248, 6.6197, 5.2536, 4.9541, 6.9495, 5.94  ,
       5.9971, 5.5419, 3.458 , 5.9253, 5.977 , 6.9099, 4.4616, 4.3659,
       6.5222, 6.6765, 5.345 , 6.134 , 5.1545, 5.8379, 6.1841, 5.6238,
       5.0158, 5.3141, 5.2627, 4.8522, 6.0906, 5.5801, 5.8643, 6.2298,
       5.8122, 6.5537, 6.0096, 4.5984, 5.8458, 4.0232, 6.2603, 5.7511,
       5.3703, 4.3772, 5.6858, 5.8271, 6.2363, 4.8972, 5.5354, 5.9876,
       4.3903, 6.3076, 4.4276, 6.0085, 5.6522, 4.8553, 5.5556, 5.203 ,
       5.5151, 5.2685, 2.6864, 5.3408, 6.5775, 5.6437, 4.2822, 5.665 ,
       5.4699, 4.8288, 5.8839, 3.8271, 4.7013, 4.3993, 6.0587, 4.6143,
       5.2502, 4.4495, 4.7888, 5.2223, 4.8007, 5.5788, 6.9282, 5.3638,
       2.8387, 5.95  , 5.9682, 4.1857, 5.8669, 6.8584, 4.9772, 4.5094,
       4.9958, 6.5542, 3.9083, 6.8436, 5.8531, 5.3666, 4.2706, 5.8384,
       4.517 , 6.6104, 6.737 , 2.5967, 4.9444, 3.0011, 5.6714, 4.9704,
       3.3472, 3.7154, 6.1542, 4.932 , 5.811 , 3.2677, 4.4686, 5.0447,
       6.595 , 6.7257, 6.1923, 3.6292, 5.36  , 6.6425, 5.7385, 3.1676,
       5.5967, 6.3505, 5.6097, 5.452 , 3.1206, 4.6423, 6.2686, 5.1252,
       6.1156, 6.4128, 5.824 , 5.3246, 5.1626, 5.8667, 5.8886, 3.702 ,
       6.3174, 5.8418, 5.2729, 6.452 , 5.9618, 5.3369, 6.0671, 5.05  ,
       3.1825, 6.5986, 4.2887, 5.33  , 5.3598, 4.8462, 5.346 , 6.4579,
       4.8886, 6.343 , 4.6351, 6.0702, 4.3524, 3.5114, 4.9818, 5.2779,
       4.5312, 5.3138, 5.029 , 6.272 , 5.7738, 4.61  , 6.5027, 5.4173,
       5.9889, 6.5954, 6.0618, 3.9898, 5.663 , 5.3317, 4.2895, 5.9338,
       4.9697, 6.2614, 5.4633, 4.883 , 6.2437, 6.1736, 5.104 , 4.8339,
       6.347 , 6.8319, 5.0765, 6.5905, 5.4847, 5.0378, 5.0018, 4.8083,
       4.3523, 4.6331, 5.7262, 6.312 , 4.571 , 4.3779, 4.4398, 4.7728,
       4.3143, 5.0938, 5.733 , 6.3561, 5.6006, 6.0311, 5.1952, 6.2407,
       6.3106, 4.9411, 4.9558, 4.7712, 5.0192, 6.9416, 5.5701, 5.4299,
       5.3178, 6.8423, 5.8759, 6.1515, 5.3396, 6.7484, 6.2499, 6.4317,
       6.375 , 6.2985, 6.0654, 5.6349, 4.3102, 5.024 , 6.1115, 6.393 ,
       5.5344, 4.8936, 5.5982, 4.9834, 4.4514, 5.7877, 5.2743, 4.3299,
       5.2915, 5.3807, 5.1052, 5.4208, 6.4392, 4.3406, 5.6806, 5.1827,
       3.8683, 5.4676, 5.72  , 3.8434, 5.1025, 6.0889, 5.2651, 4.995 ,
       4.4686, 4.223 , 6.7024, 5.8389, 5.9438, 4.893 , 5.9772, 5.3429,
       3.4701, 4.8005, 3.4147, 6.8408, 5.6824, 4.4424, 6.5628, 5.9024,
       6.1255, 6.1345, 6.4309, 5.6124, 5.4196, 4.5663, 6.5443, 6.7732,
       4.5635, 5.1099, 4.8507, 6.7651, 5.1233, 2.5412, 6.5132, 5.5081,
       5.17  , 5.7496, 5.5283, 6.5481, 5.3603, 3.8818, 4.5278, 5.1067,
       5.7404, 6.6118, 4.7614, 6.4121, 4.1473, 5.2092, 6.092 , 3.5642,
       3.4821, 5.5598, 5.9845, 5.8625, 6.6388, 5.8655, 5.5324, 3.9004,
       4.6509, 5.6264, 4.9879, 4.0643, 4.9079, 4.8361, 5.9138, 6.8184,
       5.335 , 5.3193, 5.2034, 4.3238, 5.7057, 4.4462, 6.3774, 5.2788,
       5.4435, 5.6439, 6.1686, 5.17  , 6.1548, 5.732 , 6.4281, 5.7221,
       3.7246, 3.5987, 5.7389, 3.8091, 4.9795, 4.6358, 4.9137, 6.5034,
       5.0308, 5.3536, 6.4972, 6.0028, 6.2356, 6.2904, 6.2087, 6.1284,
       4.7324, 5.5653, 6.4885, 6.9312, 6.2294, 4.6231, 5.3355, 6.6339,
       6.7278, 6.2682, 5.1963, 4.2826, 4.8768, 4.3939, 6.2303, 5.7596,
       6.598 , 4.8743, 6.7203, 5.2328, 6.2638, 3.6273, 4.9625, 4.7016,
       5.2357, 6.7528, 4.9343, 5.5994, 4.5853, 5.4781, 5.165 , 6.5961,
       6.0125, 5.9494, 4.5406, 5.1728, 3.0294, 6.3239, 4.0326, 6.7575,
       6.3916, 6.4248, 6.6452, 6.7889, 6.0131, 4.4894, 5.0135, 4.3713,
       5.5836, 3.6974, 6.5293, 4.0125, 4.7548, 6.392 , 4.5406, 4.9644,
       5.209 , 5.9525, 5.5885, 6.7059, 5.7045, 6.4103, 5.2879, 5.4495,
       6.6978, 6.6298, 6.2852, 4.0275, 5.4515, 6.6869, 5.4789, 4.4572,
       5.9957, 4.2768, 5.9946, 6.4475, 6.2141, 4.0081, 4.9263, 5.0207,
       6.1738, 4.5855, 4.8871, 6.7219, 5.2101, 5.9864, 3.4704, 5.9126,
       3.9767, 6.3066, 6.4034, 4.0552, 5.2495, 6.0707, 3.8863, 5.6626,
       6.9299, 6.523 , 4.5838, 4.0444, 4.1575, 5.5496, 4.579 , 6.1206,
       4.9765, 5.5361, 6.2052, 6.137 , 6.5713, 5.785 , 5.2765, 5.3517,
       2.9252, 6.4814, 4.5031, 6.0467, 5.8322, 4.6042, 6.0123, 6.1025,
       5.8111, 5.6511, 6.0011, 5.5118, 5.4033, 4.6064, 2.3682, 5.3773,
       6.0904, 4.5266, 6.5242, 4.8678, 6.525 , 6.6584, 4.4853, 5.5714,
       4.6006, 4.5629, 5.7017, 4.0073, 5.3099, 5.639 , 6.3744, 5.2154,
       5.0975, 4.1481, 4.4175, 3.4413, 3.1084, 5.6884, 4.3428, 3.157 ,
       6.5348, 6.4367, 4.3542, 5.3318, 5.9686, 6.3177, 6.2221, 5.8436,
       5.1785, 4.7783, 5.8939, 6.1095, 4.5063, 3.2883, 4.669 , 5.9279,
       5.5243, 4.6682, 6.6339, 4.8822, 4.3383, 5.6031, 5.2064, 4.083 ,
       5.4162, 6.3299, 4.5831, 6.3066, 4.0067, 3.7314, 6.6283, 4.6214,
       5.8542, 4.4487, 5.8168, 5.3792, 5.1649, 5.8142, 4.525 , 6.6483,
       4.6288, 6.6941, 6.085 , 6.1871, 6.1853, 5.0039, 5.7615, 6.725 ,
       6.1013, 5.6964, 6.4444, 5.8025, 6.0491, 5.2631, 4.9807, 4.4397,
       4.8079, 5.7967, 6.7894, 6.0756, 5.1182, 6.2434, 4.5199, 5.4628,
       6.6621, 6.0667, 5.7486, 5.4098, 3.8065, 5.9855, 5.3811, 4.4154,
       5.8237, 4.636 , 3.2859, 6.4152, 5.4022, 4.0583, 4.5296, 5.9253,
       6.7262, 3.9731, 6.4449, 5.165 , 6.6614, 6.1548, 5.9861, 5.5985,
       6.3628, 6.1522, 5.6702, 5.8887, 5.6326, 6.8494, 6.173 , 5.5859,
       4.3053, 6.5367, 5.1757, 4.0337, 5.2365, 5.4027, 4.834 , 4.2339,
       5.5758, 4.4815, 6.0288, 5.7459, 6.1678, 5.6696, 5.1114, 6.8377,
       4.5704, 3.7812, 2.7896, 5.7203, 4.2484, 4.3866, 5.7516, 5.542 ,
       3.9074, 5.1989, 6.7897, 5.6032, 6.4615, 5.5304, 5.1978, 4.6524,
       5.748 , 5.1215, 3.2855, 4.2649, 5.5226, 5.4981, 6.8257, 6.5995,
       6.5629, 5.8126, 3.4339, 6.2554, 6.7622, 6.4506, 5.6935, 6.69  ,
       4.8029, 5.213 , 4.1588, 3.7464, 6.93  , 3.5095, 4.2357, 6.4759])

In [273]:
np.exp(total)

/tmp/ipykernel_1986/190601779.py:1: RuntimeWarning: overflow encountered in exp
  np.exp(total)

array([2.6019e+238, 6.9040e+034, 7.7330e+147, 2.4595e+212, 3.2143e+275,
       3.7186e+272, 2.2389e+188,         inf, 1.1743e+033, 1.0535e+075,
       2.5826e+026, 3.3977e+046, 1.1173e+107, 8.9202e+196,         inf,
       2.6491e+256, 1.0691e+220, 4.6235e+198, 6.1669e+074, 5.6799e+036,
       1.4968e+196, 2.2860e+120, 1.9011e+030, 6.2862e+078, 1.7713e+121,
       7.1153e+191, 1.9294e+015, 9.0501e+079, 2.9165e+201, 1.4146e+102,
       4.1757e+214,         inf, 4.3213e+305, 1.2099e+088, 2.2169e+181,
       1.1570e+031, 5.9770e+142, 7.1873e+249, 2.2501e+200, 7.5854e+109,
       3.5085e+039, 1.4906e+051, 1.3066e+189,         inf, 1.0417e+014,
       2.4350e+171, 4.5757e+232, 1.3265e+082, 6.2162e+051,         inf,
       5.6845e+291, 4.6479e+101, 3.9404e+032, 1.0870e+007, 5.4729e+014,
               inf, 2.7472e+040,         inf,         inf, 5.6318e+083,
       6.9985e+033, 3.0224e+152, 1.0276e+226, 1.2447e+072, 1.4209e+138,
       2.3370e+072, 3.3516e+030, 1.1651e+267,         inf, 2.2838e+008,
               inf, 1.8746e+283, 2.3807e+066, 4.9426e+207, 2.8305e+306,
       8.4690e+189, 1.8375e+201, 1.3265e+082,         inf, 2.9332e+046,
       2.4509e+271, 1.8235e+132, 1.6804e+070, 3.7984e+146, 3.2889e+111,
       1.3579e+265, 2.9453e+174, 4.2086e+157, 2.3265e+019, 4.4555e+210,
       2.6477e+086, 3.6790e+204, 1.4507e+070, 1.3765e+264, 8.4494e+040,
       2.0223e+044,         inf, 1.1585e+034, 1.4570e+072, 1.8697e+226,
       1.6301e+022,         inf, 4.7994e+094, 2.5268e+159, 7.5710e+096,
               inf, 8.1883e+074, 9.7974e+169, 2.8624e+139,         inf,
       1.0944e+015, 2.2594e+134, 3.2357e+232, 2.1091e+238,         inf,
       9.2067e+036, 1.0573e+050, 2.6341e+023, 9.5194e+049, 5.4735e+048,
               inf, 2.1415e+182,         inf, 1.4073e+233, 1.0156e+206,
       1.1602e+299, 3.4000e+073, 1.6694e+130, 1.0939e+250,         inf,
       2.9484e+126, 1.1824e+252, 3.5436e+063, 1.8537e+239, 2.7624e+222,
       2.6513e+123, 9.7277e+059, 1.4963e+094, 5.1806e+236, 3.0573e+264,
               inf,         inf,         inf, 7.3661e+013, 1.8858e+213,
       3.7146e+126, 2.7617e+137, 4.3832e+120, 1.4144e+262, 2.6090e+118,
       9.3828e+166, 2.0785e+110,         inf, 1.2308e+045, 2.4239e+295,
       2.6635e+210, 8.1318e+032, 4.3723e+114,         inf, 3.3128e+255,
       3.3406e+157, 1.1047e+029, 1.4609e+146, 4.7666e+069, 8.8649e+181,
       1.9884e+155,         inf,         inf, 2.0180e+140, 8.1718e+221,
       4.2269e+159, 3.2937e+182, 1.1543e+076, 5.1282e+144, 1.5681e+072,
       7.6237e+138, 7.5473e+080, 7.1346e+071, 1.3796e+202, 5.5564e+118,
       1.3245e+205, 2.1948e+140, 4.8021e+070, 1.4635e+125, 2.4551e+039,
       5.4193e+024,         inf, 5.7942e+084, 5.9786e+033, 2.1678e+127,
       2.4709e+105, 1.1261e+067,         inf, 4.0192e+046, 3.8046e+074,
       7.5322e+033, 7.1648e+039, 3.4078e+011, 4.9834e+075, 5.9222e+162,
       2.4858e+052, 7.3093e+104, 1.0585e+196, 1.2776e+118, 3.2841e+040,
       3.2887e+094, 3.4445e+273, 1.2573e+130, 3.5237e+041,         inf,
       4.4678e+107,         inf, 3.8464e+210, 3.1904e+063, 3.2887e+094,
       2.1669e+008, 2.9974e+056, 2.9521e+129,         inf, 2.7714e+078,
       1.2026e+124, 1.4567e+198, 8.4595e+026, 5.2282e+005, 2.7848e+039,
       3.1012e+079, 5.0145e+284, 3.9701e+067, 1.4461e+248, 2.2953e+231,
       1.6253e+074, 3.0719e+014,         inf, 4.4709e+134, 7.0987e+236,
       8.8185e+084, 4.9614e+039, 6.6625e+100, 1.3874e+030, 7.9335e+040,
       2.2690e+102, 3.2459e+054, 1.0003e+085, 1.8876e+114,         inf,
       4.0910e+173, 2.2774e+111, 8.0173e+040, 5.8095e+141, 1.6302e+233,
       1.1093e+191, 2.9488e+160, 1.3303e+013, 2.0935e+043, 7.4394e+214,
       3.1629e+059, 1.8039e+030, 7.7838e+070, 6.6863e+058, 1.8923e+120,
       1.1284e+308, 1.0125e+030, 7.2545e+069, 2.6088e+101, 6.7562e+024,
               inf, 4.9956e+064,         inf, 1.0774e+129, 1.1632e+162,
       5.5399e+153, 1.8274e+019, 2.5232e+088, 9.3666e+010, 6.4874e+272,
       1.3284e+153, 3.1711e+099, 1.1210e+174,         inf, 5.4357e+200,
       1.6567e+255, 7.4532e+016, 9.8897e+006, 1.3816e+273, 8.9503e+086,
       1.0801e+152, 1.3704e+034, 2.9646e+097, 7.0315e+154, 7.2958e+302,
       5.9117e+183, 7.9249e+088, 3.1007e+028, 1.4487e+033, 3.8306e+082,
       2.3988e+118, 4.0292e+052, 2.8315e+214, 2.8870e+109, 2.5526e+040,
       1.0906e+091, 6.1506e+017, 1.4676e+022, 2.3575e+093, 3.7599e+054,
       2.9312e+230, 2.6107e+128,         inf, 1.6802e+036, 5.0516e+074,
       4.9305e+218, 1.6992e+063, 2.7865e+032, 6.5840e+063,         inf,
       4.2391e+090, 6.8869e+028, 3.3469e+170, 5.1115e+094, 2.4283e+080,
       1.2783e+094, 9.4598e+017, 5.6520e+041, 6.8936e+140, 7.5842e+058,
       1.9114e+178, 3.1841e+227, 8.5844e+171, 1.8323e+093, 2.0988e+066,
       2.3545e+090, 1.0188e+045, 4.0658e+175, 2.5953e+021, 3.2861e+033,
       7.3673e+064,         inf, 3.5843e+158, 1.5364e+065, 5.4554e+175,
       6.1440e+065, 4.5693e+178, 2.9495e+245, 1.7095e+221, 1.2090e+061,
               inf, 6.4545e+032,         inf, 1.1416e+083, 3.6412e+061,
               inf, 9.9497e+164, 5.0314e+174, 6.4601e+110, 6.1620e+013,
       3.9323e+162, 1.7040e+171,         inf, 4.1760e+037, 1.5382e+034,
       2.2287e+295,         inf, 1.0240e+091, 2.1576e+200, 1.6722e+075,
       9.7124e+148, 4.1834e+210, 1.8923e+120, 3.0403e+065, 1.7289e+088,
       6.6621e+083, 3.9504e+055, 6.6809e+191, 1.3590e+115, 9.2958e+152,
       3.0231e+220, 1.5939e+145, 6.4600e+304, 7.8540e+176, 1.3755e+043,
       1.4892e+150, 1.8570e+024, 1.9851e+227, 4.0005e+136, 2.2135e+093,
       3.7551e+034, 9.2322e+127, 2.4109e+147, 8.0865e+221, 1.4435e+058,
       1.2556e+110, 1.1363e+173, 1.0731e+035, 2.0437e+238, 2.3024e+036,
       5.0532e+176, 5.4714e+123, 5.9496e+055, 2.2000e+112, 9.1739e+078,
       7.6323e+107, 2.0276e+084, 2.3714e+006, 4.2838e+090,         inf,
       4.8386e+122, 2.7659e+031, 2.1358e+125, 1.2966e+103, 2.0450e+054,
       1.0017e+156, 8.8276e+019, 6.4948e+047, 2.2379e+035, 6.2574e+185,
       6.7150e+043, 5.9538e+082, 1.4768e+037, 1.5335e+052, 3.1905e+080,
       6.3954e+052, 9.6100e+114,         inf, 5.4204e+092, 2.6536e+007,
       4.6431e+166, 5.2731e+169, 3.5542e+028, 2.3916e+153,         inf,
       1.0052e+063, 2.9043e+039, 1.5412e+064, 9.3290e+304, 4.2961e+021,
               inf, 1.8509e+151, 9.9659e+092, 1.2067e+031, 1.1489e+149,
       5.8077e+039,         inf,         inf, 6.7266e+005, 9.2989e+060,
       5.4023e+008, 1.3556e+126, 3.7461e+062, 2.2089e+012, 6.9037e+017,
       2.5745e+204, 1.6618e+060, 1.0808e+145, 2.5132e+011, 7.6779e+037,
       2.5013e+067,         inf,         inf, 2.3093e+212, 2.3236e+016,
       2.4404e+092,         inf, 7.7183e+134, 2.0650e+010, 1.1417e+117,
       5.6627e+248, 3.8476e+118, 1.9443e+101, 6.9291e+009, 1.1802e+045,
       1.5825e+229, 1.1290e+073, 4.7508e+196, 5.5043e+264, 8.4366e+146,
       1.4724e+089, 6.8286e+075, 2.2222e+153, 5.3748e+156, 3.9990e+017,
       4.6070e+240, 3.7241e+149, 4.7963e+084, 2.1795e+275, 4.2875e+168,
       1.8689e+090, 2.3669e+187, 5.7939e+067, 2.9510e+010,         inf,
       4.4365e+031, 4.4814e+089, 2.3400e+092, 1.8549e+055, 1.2633e+091,
       9.1570e+276, 4.5478e+057, 7.9731e+246, 5.5999e+044, 8.8870e+187,
       5.3827e+033, 3.5212e+014, 1.9682e+063, 1.2602e+085, 2.1578e+040,
       1.6234e+088, 2.2353e+066, 9.2351e+229, 5.5465e+139, 4.3660e+043,
       4.4456e+289, 6.8671e+097, 1.8419e+173,         inf, 2.4246e+186,
       2.9566e+023, 1.2115e+125, 6.4716e+089, 4.7250e+031, 9.5700e+163,
       3.4083e+062, 3.6117e+227, 2.7410e+102, 2.1807e+057, 3.6566e+223,
       2.6243e+208, 3.3150e+071, 3.9212e+054, 7.7020e+247,         inf,
       3.7834e+069,         inf, 4.5093e+104, 8.6615e+066, 3.7231e+064,
       1.6282e+053, 5.3265e+033, 4.5871e+044, 1.7615e+133, 2.2393e+239,
       9.3559e+041, 3.9992e+034, 6.4426e+036, 2.2686e+051, 2.9367e+032,
       6.1783e+070, 1.4385e+134, 1.3927e+250, 3.2627e+117, 5.5438e+180,
       2.2230e+078, 7.8116e+222, 1.0514e+239, 5.8585e+060, 4.6847e+061,
       1.8779e+051, 5.0328e+065,         inf, 9.6396e+113, 1.1818e+099,
       3.6822e+088,         inf, 5.6401e+154, 7.3026e+203, 3.2948e+090,
               inf, 8.8990e+224, 6.3446e+269, 8.2845e+254, 1.4091e+236,
       1.1349e+187, 4.1462e+121, 2.1658e+032, 1.0496e+066, 7.5641e+195,
       3.5218e+259, 9.7593e+109, 8.9053e+057, 1.7016e+117, 2.4797e+063,
       1.7287e+037, 4.9111e+141, 6.3019e+084, 9.5189e+032, 1.8528e+086,
       2.0938e+094, 4.0047e+071, 1.5093e+098, 6.7156e+271, 2.1591e+033,
       2.0354e+127, 2.3749e+077, 6.0940e+020, 7.5106e+102, 2.6612e+132,
       1.8800e+020, 2.5766e+071, 3.1369e+191, 1.0464e+084, 1.3587e+064,
       7.6779e+037, 4.3255e+029,         inf, 1.3879e+149, 4.3274e+165,
       8.1878e+057, 1.7958e+171, 6.5886e+090, 9.0874e+013, 6.2625e+052,
       1.6070e+013,         inf, 3.3693e+127, 8.0320e+036, 3.7863e+307,
       8.1300e+158, 4.3412e+198, 2.7469e+200, 3.8329e+269, 8.1089e+118,
       1.1487e+098, 5.9567e+041, 8.6572e+301,         inf, 4.5336e+041,
       8.7099e+071, 3.2701e+055,         inf, 8.2390e+072, 3.2595e+005,
       5.1560e+292, 1.3497e+107, 2.5106e+076, 2.4680e+136, 2.0849e+109,
       1.2862e+303, 2.5720e+092, 1.1685e+021, 1.5747e+040, 5.1524e+071,
       1.4043e+135,         inf, 5.9165e+050, 3.6166e+264, 2.9823e+027,
       2.8513e+079, 1.2544e+192, 2.1657e+015, 1.3402e+014, 6.5566e+112,
       3.2232e+172, 5.0031e+152,         inf, 1.4601e+153, 5.8957e+109,
       2.9131e+021, 2.8811e+045, 3.9051e+120, 4.8049e+063, 1.9307e+025,
       6.0834e+058, 5.1521e+054, 5.5366e+160,         inf, 1.2806e+090,
       5.0456e+088, 9.7705e+078, 5.9971e+032, 3.4450e+130, 1.1122e+037,
       3.5282e+255, 1.5224e+085, 2.6724e+100, 5.2626e+122, 2.4716e+207,
       2.5106e+076, 3.5277e+204, 1.0280e+134, 6.5679e+268, 4.9967e+132,
       1.0075e+018, 7.4762e+015, 8.7548e+134, 3.8918e+019, 1.4065e+063,
       6.0270e+044, 1.3371e+059, 6.9096e+289, 2.9370e+066, 6.2324e+091,
       1.1630e+288, 4.9116e+175, 5.7184e+221, 1.7127e+234, 7.4948e+215,
       1.6130e+199, 2.0987e+049, 2.7343e+113, 3.6483e+285,         inf,
       2.3995e+220, 1.6393e+044, 1.4224e+090,         inf,         inf,
       1.2430e+229, 2.7138e+078, 2.8544e+031, 9.6141e+056, 1.4398e+035,
       3.8087e+220, 5.8817e+137,         inf, 6.9430e+056,         inf,
       2.2493e+081, 1.2733e+228, 2.1590e+016, 1.2053e+062, 6.7026e+047,
       3.8830e+081,         inf, 2.2771e+060, 2.3562e+117, 3.7413e+042,
       9.3347e+103, 1.0503e+076,         inf, 2.5458e+177, 3.6469e+166,
       5.1582e+040, 4.0696e+076, 9.6246e+008, 1.6363e+242, 3.1392e+024,
               inf, 1.5690e+259, 8.9332e+267,         inf,         inf,
       3.2412e+177, 4.8224e+038, 2.1275e+065, 2.3658e+034, 3.4237e+115,
       3.3103e+017, 2.8497e+297, 1.0207e+024, 2.7490e+050, 1.9561e+259,
       5.1582e+040, 1.5836e+062, 2.7340e+079, 1.2072e+167, 1.2720e+116,
               inf, 2.4108e+130, 1.2135e+264, 9.0727e+085, 1.0799e+101,
               inf,         inf, 1.0938e+233, 2.3642e+024, 1.7141e+101,
               inf, 1.1277e+104, 2.8615e+037, 2.8241e+174, 1.8755e+031,
       1.8556e+174, 1.2664e+274, 1.0677e+217, 8.0168e+023, 7.4818e+059,
       6.3406e+065, 2.9767e+208, 3.8207e+042, 3.7253e+057,         inf,
       3.3729e+079, 7.0102e+172, 9.1834e+013, 3.5622e+160, 1.4631e+023,
       1.1592e+238, 1.8198e+262, 1.1421e+025, 5.3043e+082, 1.1079e+188,
       1.4568e+021, 1.0907e+125,         inf, 3.8474e+295, 3.2298e+042,
       6.1470e+024, 5.7185e+027, 4.7496e+111, 2.0349e+042, 4.5414e+197,
       9.0496e+062, 1.4853e+110, 1.2978e+215, 8.6277e+200,         inf,
       2.0330e+141, 9.5913e+084, 4.1819e+091, 1.2421e+008, 3.5199e+283,
       1.6474e+039, 3.8842e+183, 1.3633e+148, 2.4506e+043, 2.3407e+177,
       1.3002e+194, 1.1153e+145, 3.9513e+123, 2.5083e+175, 3.3649e+107,
       2.9738e+096, 3.0552e+043, 4.3412e+004, 9.9352e+093, 6.0149e+191,
       1.4030e+040, 8.8189e+295, 2.9661e+056, 1.5065e+296,         inf,
       3.3393e+038, 1.3489e+114, 1.6970e+043, 4.3017e+041, 1.0299e+130,
       7.6871e+023, 7.4640e+087, 1.2887e+122, 5.9203e+254, 8.8620e+079,
       1.1359e+071, 3.1431e+027, 9.9395e+035, 3.6451e+013, 5.2737e+009,
       1.9662e+128, 2.5541e+033, 1.6050e+010, 1.2751e+299, 1.3902e+271,
       6.1700e+033, 6.5399e+089, 6.1081e+169, 5.3365e+240, 5.8941e+218,
       6.9193e+149, 1.1151e+077, 4.3499e+051, 3.7104e+157, 3.0024e+195,
       2.1873e+039, 4.3387e+011, 1.9681e+046, 1.0441e+163, 7.6088e+108,
       1.7907e+046,         inf, 1.9633e+057, 1.8061e+033, 6.5244e+117,
       1.6867e+079, 5.8146e+025, 5.2817e+097, 4.7106e+243, 3.0326e+042,
       1.1838e+238, 7.4487e+023, 1.3377e+018,         inf, 1.3858e+044,
       2.7584e+151, 1.3721e+037, 7.5395e+145, 1.4963e+094, 1.0177e+076,
       3.1210e+145, 1.2112e+040,         inf, 2.9513e+044,         inf,
       5.6060e+190, 1.8195e+211, 7.6113e+210, 5.1016e+064, 1.0814e+138,
               inf, 7.6912e+193, 2.1544e+129, 1.7407e+273, 6.4130e+143,
       1.0643e+184, 7.0953e+083, 1.6814e+063, 6.3753e+036, 1.5449e+053,
       9.2898e+142,         inf, 9.3372e+188, 3.4829e+072, 3.0911e+223,
       7.5510e+039, 2.4165e+102,         inf, 1.9593e+187, 1.8012e+136,
       1.2665e+097, 3.4673e+019, 4.8036e+172, 2.2535e+094, 8.4024e+035,
       7.6758e+146, 6.1549e+044, 4.0738e+011, 2.4448e+265, 2.3113e+096,
       1.3653e+025, 1.8628e+040, 4.0157e+162,         inf, 1.2111e+023,
       2.4358e+273, 1.0393e+076,         inf, 3.5277e+204, 6.0518e+172,
       1.8507e+117, 6.6369e+251, 1.0436e+204, 9.5866e+125, 5.6054e+156,
       2.1624e+121,         inf, 2.0184e+208, 6.3612e+115, 1.4997e+032,
       4.6882e+299, 6.8794e+076, 3.3433e+024, 4.4509e+081, 2.6217e+096,
       3.9626e+054, 9.1160e+029, 4.3723e+114, 2.3864e+038, 2.1548e+180,
       7.6946e+135, 1.6411e+207, 8.1896e+125, 1.1206e+072,         inf,
       8.7847e+041, 1.1274e+019, 1.1699e+007, 2.8342e+132, 2.4979e+030,
       7.9973e+034, 4.6340e+136, 6.6668e+110, 4.1194e+021, 4.3530e+078,
               inf, 6.5932e+117, 9.2251e+277, 3.5617e+109, 3.5657e+078,
       3.3726e+045, 1.5226e+136, 6.0127e+072, 4.0312e+011, 8.0121e+030,
       4.9471e+108, 1.1688e+106,         inf,         inf, 4.1615e+307,
       1.8270e+145, 2.8933e+013, 1.5155e+226,         inf, 9.0222e+274,
       9.1076e+128,         inf, 8.4029e+052, 5.7018e+079, 6.2196e+027,
       2.5117e+018,         inf, 3.3062e+014, 1.0340e+030, 9.7045e+281])

In [274]:
np.log10(total)

array([2.7395, 1.9043, 2.5321, 2.6894, 2.8023, 2.7977, 2.6372, 2.8878,
       1.8816, 2.2374, 1.784 , 2.03  , 2.3918, 2.6566, 2.8748, 2.7712,
       2.7047, 2.6603, 2.2361, 1.9275, 2.6549, 2.4427, 1.8434, 2.2587,
       2.4459, 2.6452, 1.5465, 2.2651, 2.6664, 2.3715, 2.6939, 2.8679,
       2.8474, 2.3071, 2.6207, 1.8545, 2.5169, 2.7599, 2.664 , 2.4031,
       1.9593, 2.0713, 2.6389, 2.9186, 1.5089, 2.5962, 2.7289, 2.2767,
       2.0765, 2.9383, 2.8272, 2.3694, 1.8754, 1.2096, 1.5307, 2.8587,
       1.969 , 2.8766, 2.8806, 2.2852, 1.8917, 2.5454, 2.7163, 2.2201,
       2.5026, 2.2218, 1.8469, 2.7888, 2.9176, 1.2844, 2.9729, 2.8144,
       2.1842, 2.6796, 2.8486, 2.6408, 2.666 , 2.2767, 2.915 , 2.0294,
       2.7958, 2.4836, 2.2087, 2.5283, 2.4096, 2.7857, 2.6039, 2.5598,
       1.6493, 2.6858, 2.2988, 2.673 , 2.2083, 2.784 , 1.9742, 2.0087,
       2.965 , 1.8945, 2.2205, 2.7168, 1.7088, 2.8706, 2.3385, 2.5647,
       2.3484, 2.969 , 2.2368, 2.5926, 2.5067, 2.9348, 1.5394, 2.4905,
       2.7287, 2.7394, 2.8828, 1.93  , 2.0614, 1.7318, 2.061 , 2.0501,
       2.9224, 2.6231, 2.9753, 2.7298, 2.6761, 2.838 , 2.2287, 2.4769,
       2.7602, 2.931 , 2.4642, 2.7637, 2.1653, 2.7411, 2.7094, 2.4536,
       2.1403, 2.3362, 2.7364, 2.7846, 2.9745, 2.9778, 2.8575, 1.5042,
       2.6912, 2.4645, 2.5003, 2.4437, 2.7808, 2.4356, 2.5849, 2.4049,
       2.8958, 2.0163, 2.8326, 2.6853, 1.8795, 2.4216, 2.9632, 2.7696,
       2.5596, 1.8253, 2.5271, 2.2053, 2.6222, 2.5534, 3.0016, 3.0167,
       2.5093, 2.7084, 2.5653, 2.6235, 2.2434, 2.5227, 2.2207, 2.5049,
       2.27  , 2.2187, 2.6679, 2.4368, 2.6742, 2.5094, 2.2115, 2.4597,
       1.9576, 1.7555, 2.8997, 2.2904, 1.8908, 2.4672, 2.385 , 2.1886,
       2.9189, 2.0306, 2.2348, 1.8921, 1.9627, 1.4241, 2.2413, 2.5738,
       2.0815, 2.3828, 2.6545, 2.4345, 1.9698, 2.3377, 2.7992, 2.4765,
       1.9808, 2.9743, 2.3942, 2.9451, 2.6856, 2.165 , 2.3377, 1.2832,
       2.1141, 2.4744, 2.9014, 2.2568, 2.4559, 2.6592, 1.7924, 1.1195,
       1.9582, 2.2625, 2.8166, 2.1922, 2.7569, 2.7265, 2.2327, 1.5232,
       2.9002, 2.4914, 2.7367, 2.2914, 1.961 , 2.3658, 1.8414, 1.9739,
       2.3723, 2.0987, 2.2916, 2.4202, 2.8968, 2.6018, 2.4089, 1.974 ,
       2.5138, 2.73  , 2.6434, 2.5676, 1.4803, 1.9989, 2.6944, 2.1367,
       1.843 , 2.2128, 2.1318, 2.4424, 2.8508, 1.8394, 2.2064, 2.3683,
       1.7572, 2.8593, 2.1731, 2.8939, 2.4729, 2.5719, 2.549 , 1.6469,
       2.3087, 1.4025, 2.7981, 2.5473, 2.36  , 2.6029, 2.8724, 2.6648,
       2.7691, 1.5894, 1.207 , 2.7986, 2.3015, 2.5442, 1.8954, 2.3511,
       2.5521, 2.8435, 2.6265, 2.3111, 1.8169, 1.8828, 2.2791, 2.4355,
       2.0832, 2.6935, 2.4015, 1.9687, 2.3214, 1.6124, 1.7079, 2.3324,
       2.0992, 2.7248, 2.4708, 2.8726, 1.9212, 2.2356, 2.7021, 2.1631,
       1.8734, 2.1672, 2.914 , 2.3195, 1.8222, 2.594 , 2.3386, 2.2674,
       2.3358, 1.6169, 1.9829, 2.5109, 2.1322, 2.6133, 2.7192, 2.5976,
       2.3319, 2.1839, 2.3182, 2.0155, 2.6068, 1.6929, 1.8875, 2.1742,
       2.8585, 2.5624, 2.1764, 2.6071, 2.1804, 2.6142, 2.7522, 2.7071,
       2.1481, 2.8671, 1.8782, 2.8749, 2.2816, 2.1515, 3.0181, 2.5797,
       2.6045, 2.4068, 1.5018, 2.5733, 2.5958, 3.0009, 1.9376, 1.8961,
       2.8325, 2.8996, 2.3213, 2.664 , 2.2386, 2.5354, 2.6857, 2.4424,
       2.1783, 2.3079, 2.2856, 2.1073, 2.6451, 2.4234, 2.5468, 2.7056,
       2.5242, 2.8462, 2.6099, 1.9971, 2.5388, 1.7473, 2.7188, 2.4977,
       2.3323, 1.901 , 2.4693, 2.5307, 2.7084, 2.1268, 2.404 , 2.6004,
       1.9067, 2.7394, 1.9229, 2.6095, 2.4547, 2.1087, 2.4128, 2.2596,
       2.3952, 2.2881, 1.1667, 2.3195, 2.8566, 2.451 , 1.8597, 2.4603,
       2.3755, 2.0971, 2.5553, 1.6621, 2.0418, 1.9106, 2.6313, 2.004 ,
       2.2801, 1.9324, 2.0798, 2.268 , 2.0849, 2.4228, 3.0089, 2.3295,
       1.2328, 2.5841, 2.592 , 1.8178, 2.548 , 2.9786, 2.1616, 1.9584,
       2.1697, 2.8465, 1.6973, 2.9721, 2.542 , 2.3307, 1.8547, 2.5356,
       1.9617, 2.8709, 2.9258, 1.1277, 2.1473, 1.3034, 2.463 , 2.1586,
       1.4537, 1.6136, 2.6727, 2.142 , 2.5237, 1.4191, 1.9407, 2.1909,
       2.8642, 2.921 , 2.6893, 1.5762, 2.3278, 2.8848, 2.4922, 1.3757,
       2.4306, 2.758 , 2.4362, 2.3678, 1.3552, 2.0161, 2.7224, 2.2259,
       2.656 , 2.785 , 2.5293, 2.3124, 2.2421, 2.5479, 2.5574, 1.6078,
       2.7436, 2.5371, 2.29  , 2.8021, 2.5892, 2.3178, 2.6349, 2.1932,
       1.3822, 2.8657, 1.8625, 2.3148, 2.3277, 2.1047, 2.3217, 2.8046,
       2.1231, 2.7547, 2.013 , 2.6363, 1.8902, 1.525 , 2.1636, 2.2921,
       1.9679, 2.3077, 2.1841, 2.7239, 2.5075, 2.0021, 2.8241, 2.3527,
       2.6009, 2.8643, 2.6326, 1.7327, 2.4594, 2.3155, 1.8629, 2.577 ,
       2.1583, 2.7193, 2.3727, 2.1207, 2.7116, 2.6812, 2.2166, 2.0994,
       2.7565, 2.9671, 2.2047, 2.8622, 2.382 , 2.1879, 2.1723, 2.0882,
       1.8902, 2.0121, 2.4869, 2.7412, 1.9852, 1.9013, 1.9282, 2.0728,
       1.8737, 2.2122, 2.4898, 2.7604, 2.4323, 2.6193, 2.2562, 2.7103,
       2.7407, 2.1459, 2.1523, 2.0721, 2.1798, 3.0147, 2.4191, 2.3582,
       2.3095, 2.9716, 2.5518, 2.6716, 2.3189, 2.9308, 2.7143, 2.7933,
       2.7686, 2.7354, 2.6342, 2.4472, 1.8719, 2.1819, 2.6542, 2.7764,
       2.4036, 2.1253, 2.4313, 2.1643, 1.9332, 2.5136, 2.2906, 1.8804,
       2.2981, 2.3368, 2.2171, 2.3542, 2.7965, 1.8851, 2.4671, 2.2508,
       1.68  , 2.3745, 2.4842, 1.6692, 2.216 , 2.6444, 2.2866, 2.1693,
       1.9407, 1.834 , 2.9108, 2.5358, 2.5814, 2.125 , 2.5959, 2.3204,
       1.5071, 2.0848, 1.483 , 2.9709, 2.4678, 1.9293, 2.8502, 2.5634,
       2.6603, 2.6642, 2.7929, 2.4374, 2.3537, 1.9831, 2.8421, 2.9416,
       1.9819, 2.2192, 2.1066, 2.9381, 2.225 , 1.1036, 2.8287, 2.3921,
       2.2453, 2.497 , 2.4009, 2.8438, 2.3279, 1.6858, 1.9664, 2.2178,
       2.493 , 2.8715, 2.0678, 2.7847, 1.8011, 2.2623, 2.6457, 1.5479,
       1.5123, 2.4146, 2.599 , 2.5461, 2.8832, 2.5474, 2.4027, 1.6939,
       2.0198, 2.4435, 2.1662, 1.7651, 2.1315, 2.1003, 2.5683, 2.9612,
       2.317 , 2.3102, 2.2598, 1.8778, 2.4779, 1.931 , 2.7697, 2.2926,
       2.3641, 2.4511, 2.679 , 2.2453, 2.673 , 2.4894, 2.7917, 2.4851,
       1.6176, 1.5629, 2.4924, 1.6543, 2.1626, 2.0133, 2.134 , 2.8244,
       2.1848, 2.325 , 2.8217, 2.607 , 2.7081, 2.7319, 2.6964, 2.6615,
       2.0553, 2.417 , 2.8179, 3.0102, 2.7054, 2.0078, 2.3172, 2.8811,
       2.9218, 2.7222, 2.2567, 1.8599, 2.118 , 1.9082, 2.7058, 2.5014,
       2.8655, 2.1169, 2.9186, 2.2726, 2.7204, 1.5753, 2.1552, 2.0419,
       2.2738, 2.9327, 2.1429, 2.4318, 1.9914, 2.3791, 2.2432, 2.8647,
       2.6112, 2.5838, 1.9719, 2.2465, 1.3157, 2.7464, 1.7513, 2.9347,
       2.7758, 2.7903, 2.886 , 2.9484, 2.6114, 1.9497, 2.1773, 1.8984,
       2.4249, 1.6057, 2.8356, 1.7426, 2.065 , 2.776 , 1.9719, 2.156 ,
       2.2622, 2.5851, 2.4271, 2.9123, 2.4774, 2.784 , 2.2965, 2.3667,
       2.9088, 2.8793, 2.7296, 1.7491, 2.3675, 2.9041, 2.3795, 1.9357,
       2.6039, 1.8574, 2.6034, 2.8001, 2.6987, 1.7407, 2.1395, 2.1805,
       2.6813, 1.9914, 2.1224, 2.9193, 2.2627, 2.5999, 1.5072, 2.5678,
       1.7271, 2.7389, 2.7809, 1.7612, 2.2799, 2.6365, 1.6878, 2.4593,
       3.0096, 2.8329, 1.9907, 1.7565, 1.8056, 2.4102, 1.9886, 2.6581,
       2.1613, 2.4043, 2.6949, 2.6653, 2.8539, 2.5124, 2.2915, 2.3242,
       1.2704, 2.8148, 1.9557, 2.6261, 2.5329, 1.9996, 2.6111, 2.6503,
       2.5237, 2.4542, 2.6062, 2.3937, 2.3466, 2.0006, 1.0285, 2.3353,
       2.645 , 1.9659, 2.8334, 2.1141, 2.8338, 2.8917, 1.9479, 2.4196,
       1.998 , 1.9817, 2.4762, 1.7404, 2.3061, 2.449 , 2.7684, 2.265 ,
       2.2138, 1.8015, 1.9185, 1.4945, 1.35  , 2.4704, 1.8861, 1.371 ,
       2.838 , 2.7954, 1.891 , 2.3156, 2.5921, 2.7437, 2.7022, 2.5378,
       2.249 , 2.0752, 2.5597, 2.6533, 1.957 , 1.4281, 2.0277, 2.5745,
       2.3992, 2.0274, 2.8811, 2.1203, 1.8841, 2.4334, 2.2611, 1.7732,
       2.3522, 2.749 , 1.9904, 2.7389, 1.7401, 1.6205, 2.8786, 2.0071,
       2.5425, 1.932 , 2.5262, 2.3362, 2.2431, 2.5251, 1.9652, 2.8873,
       2.0103, 2.9072, 2.6427, 2.687 , 2.6863, 2.1732, 2.5022, 2.9206,
       2.6498, 2.4739, 2.7988, 2.52  , 2.6271, 2.2857, 2.1631, 1.9281,
       2.088 , 2.5175, 2.9486, 2.6386, 2.2228, 2.7115, 1.9629, 2.3724,
       2.8933, 2.6347, 2.4966, 2.3494, 1.6531, 2.5995, 2.337 , 1.9176,
       2.5292, 2.0134, 1.427 , 2.7861, 2.3461, 1.7625, 1.9672, 2.5733,
       2.9211, 1.7255, 2.799 , 2.2431, 2.893 , 2.673 , 2.5997, 2.4314,
       2.7633, 2.6719, 2.4625, 2.5574, 2.4462, 2.9746, 2.6809, 2.4259,
       1.8697, 2.8389, 2.2478, 1.7518, 2.2742, 2.3464, 2.0994, 1.8388,
       2.4216, 1.9463, 2.6183, 2.4954, 2.6786, 2.4623, 2.2198, 2.9696,
       1.9849, 1.6422, 1.2115, 2.4843, 1.8451, 1.9051, 2.4979, 2.4068,
       1.697 , 2.2579, 2.9487, 2.4334, 2.8062, 2.4018, 2.2574, 2.0205,
       2.4963, 2.2242, 1.4269, 1.8522, 2.3984, 2.3878, 2.9643, 2.8661,
       2.8502, 2.5244, 1.4913, 2.7167, 2.9368, 2.8015, 2.4727, 2.9054,
       2.0859, 2.264 , 1.8062, 1.627 , 3.0097, 1.5242, 1.8395, 2.8124])

In [275]:
np.sqrt(total)

array([23.4301,  8.9566, 18.4533, 22.1144, 25.1869, 25.0523, 20.8253,
       27.7917,  8.7262, 13.1433,  7.7985, 10.3509, 15.6999, 21.2954,
       27.3768, 24.2989, 22.5086, 21.3879, 13.1229,  9.1995, 21.2535,
       16.6474,  8.3499, 13.47  , 16.7088, 21.018 ,  5.9326, 13.5686,
       21.5381, 15.3366, 22.2302, 27.1618, 26.5283, 14.2414, 20.4344,
        8.4573, 18.1316, 23.9857, 21.4785, 15.9062,  9.5423, 10.855 ,
       20.8676, 28.7937,  5.6813, 19.8653, 23.1456, 13.7512, 10.9206,
       29.4553, 25.9189, 15.3002,  8.6634,  4.0251,  5.8255, 26.8744,
        9.6496, 27.4343, 27.5622, 13.8868,  8.8279, 18.7376, 22.8125,
       12.8843, 17.8356, 12.9087,  8.3837, 24.798 , 28.7591,  4.3871,
       30.6519, 25.5394, 12.3628, 21.8685, 26.5637, 20.9123, 21.5274,
       13.7512, 28.675 , 10.3438, 24.9979, 17.4511, 12.7161, 18.3715,
       16.0243, 24.7081, 20.0432, 19.0511,  6.6778, 22.0236, 14.1066,
       21.7032, 12.7104, 24.6618,  9.7076, 10.1004, 30.3749,  8.8564,
       12.8904, 22.8256,  7.1516, 27.2451, 14.7652, 19.1582, 14.9356,
       30.5129, 13.1337, 19.7843, 17.9196, 29.3374,  5.8846, 17.5887,
       23.1382, 23.4257, 27.6309,  9.2257, 10.7324,  7.3436, 10.7275,
       10.5936, 28.9189, 20.4898, 30.7347, 23.1699, 21.7795, 26.2416,
       13.012 , 17.3161, 23.9945, 29.2087, 17.0648, 24.0919, 12.0966,
       23.472 , 22.6316, 16.858 , 11.7528, 14.7257, 23.3464, 24.6779,
       30.7067, 30.8261, 26.8384,  5.6507, 22.1604, 17.0716, 17.7896,
       16.667 , 24.5688, 16.5125, 19.6079, 15.9379, 28.0467, 10.1894,
       26.0796, 22.0119,  8.7051, 16.2472, 30.3105, 24.2561, 19.045 ,
        8.1777, 18.3455, 12.6665, 20.4683, 18.91  , 31.6795, 32.238 ,
       17.974 , 22.6047, 19.1717, 20.5003, 13.234 , 18.254 , 12.8933,
       17.8826, 13.6465, 12.8627, 21.5742, 16.5354, 21.7327, 17.9763,
       12.7574, 16.9766,  9.5236,  7.5467, 28.173 , 13.9705,  8.8189,
       17.1231, 15.5781, 12.4255, 28.8047, 10.3591, 13.1045,  8.832 ,
        9.5797,  5.1531, 13.2023, 19.3597, 10.9839, 15.5389, 21.2453,
       16.4909,  9.6588, 14.7524, 25.0967, 17.3079,  9.7809, 30.6993,
       15.744 , 29.6868, 22.0202, 12.0923, 14.7524,  4.3811, 11.4036,
       17.266 , 28.2296, 13.4395, 16.9028, 21.3609,  7.8742,  3.6286,
        9.5302, 13.5291, 25.6036, 12.4761, 23.9042, 23.0809, 13.072 ,
        5.7757, 28.1895, 17.6081, 23.3532, 13.9855,  9.5605, 15.2366,
        8.331 ,  9.7044, 15.352 , 11.2034, 13.99  , 16.2213, 28.0804,
       19.9939, 16.0128,  9.7049, 18.0672, 23.1731, 20.9737, 19.2223,
        5.4972,  9.9875, 22.2432, 11.7049,  8.3467, 12.7763, 11.6383,
       16.6418, 26.633 ,  8.312 , 12.6831, 15.2814,  7.5612, 26.8931,
       12.2055, 27.9875, 17.2368, 19.3176, 18.8151,  6.6597, 14.2672,
        5.0262, 25.0634, 18.7771, 15.1364, 20.0191, 27.3019, 21.4991,
       24.2418,  6.233 ,  4.0134, 25.0785, 14.1497, 18.7102,  8.8658,
       14.9812, 18.8825, 26.4077, 20.5706, 14.3073,  8.0996,  8.7382,
       13.7897, 16.51  , 11.0058, 22.2215, 15.8758,  9.6458, 14.4783,
        6.4   ,  7.1443, 14.6628, 11.21  , 23.0363, 17.1957, 27.31  ,
        9.133 , 13.1153, 22.4401, 12.0662,  8.6434, 12.1222, 28.642 ,
       14.4457,  8.1487, 19.8153, 14.7673, 13.6049, 14.7203,  6.4336,
        9.805 , 18.0081, 11.6437, 20.261 , 22.8877, 19.897 , 14.6542,
       12.3577, 14.4253, 10.1801, 20.1086,  7.022 ,  8.7849, 12.2214,
       26.8697, 19.1072, 12.2514, 20.1159, 12.3079, 20.2825, 23.7743,
       22.5701, 11.8595, 27.1374,  8.6918, 27.3807, 13.8292, 11.9059,
       32.2901, 19.4916, 20.0566, 15.9734,  5.6349, 19.3491, 19.8564,
       31.6563,  9.3073,  8.8723, 26.078 , 28.17  , 14.4762, 21.4776,
       13.1609, 18.5218, 22.0221, 16.6418, 12.2793, 14.2539, 13.8928,
       11.3144, 21.0165, 16.282 , 18.7676, 22.5316, 18.285 , 26.4925,
       20.1821,  9.9664, 18.5953,  7.4754, 22.8773, 17.7352, 14.6607,
        8.9225, 17.1654, 18.4217, 22.6045, 11.5723, 15.9221, 19.9618,
        8.9811, 23.425 ,  9.1502, 20.1711, 16.8795, 11.3325, 16.0835,
       13.484 , 15.761 , 13.9328,  3.8313, 14.446 , 26.8096, 16.8075,
        8.5087, 16.9877, 15.4086, 11.1828, 18.9527,  6.7769, 10.4925,
        9.022 , 20.6836, 10.0457, 13.8057,  9.2512, 10.9618, 13.615 ,
       11.0268, 16.2714, 31.9485, 14.6126,  4.1345, 19.5899, 19.7686,
        8.1081, 18.7928, 30.8517, 12.0444,  9.5324, 12.1572, 26.4994,
        7.0578, 30.6238, 18.663 , 14.6334,  8.4598, 18.5263,  9.5687,
       27.2546, 29.0351,  3.6632, 11.8484,  4.4841, 17.042 , 12.0034,
        5.3314,  6.4091, 21.695 , 11.7755, 18.2744,  5.1235,  9.3399,
       12.4575, 27.045 , 28.872 , 22.113 ,  6.1388, 14.5853, 27.6952,
       17.6236,  4.8735, 16.4175, 23.9327, 16.5243, 15.2717,  4.7601,
       10.1873, 22.9728, 12.9696, 21.2806, 24.6898, 18.3932, 14.3289,
       13.2142, 18.7908, 18.997 ,  6.3663, 23.5403, 18.558 , 13.9637,
       25.1792, 19.7051, 14.4173, 20.7713, 12.4912,  4.91  , 27.0938,
        8.5364, 14.3677, 14.5838, 11.281 , 14.4834, 25.2533, 11.5222,
       23.8435, 10.1507, 20.8031,  8.813 ,  5.7875, 12.0723, 13.9982,
        9.637 , 14.2517, 12.3602, 23.0112, 17.938 , 10.0242, 25.8252,
       15.0092, 19.9739, 27.0498, 20.7163,  7.3514, 16.971 , 14.3805,
        8.5401, 19.4314, 11.9994, 22.8904, 15.3581, 11.4903, 22.6886,
       21.9067, 12.8328, 11.2119, 23.891 , 30.4459, 12.6574, 26.9836,
       15.5234, 12.4149, 12.1934, 11.0691,  8.8124, 10.1409, 17.516 ,
       23.476 ,  9.8307,  8.926 ,  9.2063, 10.8743,  8.6464, 12.7672,
       17.5758, 23.9995, 16.4495, 20.4004, 13.4313, 22.6546, 23.4599,
       11.8289, 11.9165, 10.8656, 12.2998, 32.163 , 16.2006, 15.1037,
       14.2804, 30.6039, 18.8767, 21.6659, 14.4369, 29.2011, 22.7588,
       24.9247, 24.2275, 23.3185, 20.7536, 16.7342,  8.6288, 12.3296,
       21.2374, 24.4464, 15.9141, 11.5514, 16.4297, 12.0818,  9.2598,
       18.0626, 13.9735,  8.7141, 14.0939, 14.7371, 12.8402, 15.0355,
       25.0181,  8.761 , 17.1213, 13.3478,  6.918 , 15.3909, 17.462 ,
        6.8325, 12.823 , 20.9985, 13.9091, 12.152 ,  9.3399,  8.2607,
       28.5373, 18.5314, 19.5292, 11.5477, 19.8577, 14.4609,  5.6693,
       11.0258,  5.5143, 30.5821, 17.136 ,  9.2183, 26.6125, 19.1286,
       21.3864, 21.4832, 24.9146, 16.5468, 15.0264,  9.8077, 26.3673,
       29.5656,  9.7937, 12.8704, 11.3061, 29.4464, 12.9574,  3.5629,
       25.9614, 15.7059, 13.2634, 17.7216, 15.8656, 26.4185, 14.5871,
        6.9649,  9.6207, 12.85  , 17.6405, 27.2731, 10.8124, 24.6813,
        7.9538, 13.526 , 21.0315,  5.9423,  5.7034, 16.1174, 19.9303,
       18.7511, 27.644 , 18.7796, 15.8983,  7.0302, 10.2311, 16.6635,
       12.1092,  7.6304, 11.6342, 11.224 , 19.2386, 30.2415, 14.4042,
       14.2915, 13.4863,  8.6876, 17.337 ,  9.2359, 24.2574, 14.005 ,
       15.2066, 16.81  , 21.8527, 13.2634, 21.7023, 17.5663, 24.8792,
       17.48  ,  6.4385,  6.0457, 17.6271,  6.7162, 12.0584, 10.1543,
       11.668 , 25.8337, 12.3713, 14.5384, 25.7545, 20.1133, 22.5968,
       23.2238, 22.2951, 21.4171, 10.6568, 16.1616, 25.6424, 31.9961,
       22.5265, 10.09  , 14.4078, 27.5761, 28.9013, 22.9676, 13.4387,
        8.5105, 11.4546,  8.9975, 22.5368, 17.8108, 27.0851, 11.4404,
       28.7937, 13.6865, 22.9179,  6.1328, 11.956 , 10.494 , 13.7064,
       29.2652, 11.7889, 16.4396,  9.9009, 15.4726, 13.2305, 27.0605,
       20.2112, 19.5837,  9.6821, 13.2816,  4.5481, 23.6161,  7.5104,
       29.3339, 24.4299, 24.8391, 27.7327, 29.798 , 20.2172,  9.4378,
       12.2647,  8.8966, 16.3104,  6.3515, 26.1709,  7.4352, 10.7769,
       24.4344,  9.6821, 11.9675, 13.5244, 19.6143, 16.3506, 28.5873,
       17.3267, 24.6592, 14.0686, 15.2525, 28.471 , 27.5203, 23.1645,
        7.4915, 15.2676, 28.3172, 15.4787,  9.2869, 20.0422,  8.4858,
       20.0317, 25.1226, 22.3546,  7.419 , 11.7416, 12.3091, 21.9096,
        9.902 , 11.5136, 28.8162, 13.5322, 19.9497,  5.6702, 19.2272,
        7.3034, 23.4129, 24.5739,  7.5959, 13.8015, 20.8084,  6.9807,
       16.9679, 31.9748, 26.0885,  9.8935,  7.555 ,  7.9946, 16.0357,
        9.8701, 21.3336, 12.0401, 15.9273, 22.2557, 21.5098, 26.7269,
       18.0381, 13.9885, 14.5247,  4.3171, 25.5517,  9.5026, 20.5604,
       18.4687,  9.9954, 20.2091, 21.1415, 18.2752, 16.8699, 20.0966,
       15.735 , 14.9043, 10.0064,  3.2678, 14.7118, 21.014 ,  9.6147,
       26.1044, 11.4032, 26.1147, 27.9161,  9.4183, 16.2109,  9.977 ,
        9.7911, 17.3022,  7.4161, 14.2245, 16.7681, 24.2205, 13.5678,
       12.7911,  7.9571,  9.1042,  5.5881,  4.7314, 17.1874,  8.7706,
        4.8476, 26.2434, 24.9866,  8.8207, 14.3808, 19.7724, 23.5435,
       22.4441, 18.5747, 13.3195, 10.9042, 19.0478, 21.2156,  9.5175,
        5.1765, 10.3245, 19.3743, 15.8338, 10.32  , 27.5763, 11.4857,
        8.7508, 16.4705, 13.5066,  7.7023, 15.0005, 23.6871,  9.8903,
       23.4133,  7.414 ,  6.4605, 27.4985, 10.0817, 18.6736,  9.2473,
       18.3274, 14.7257, 13.2293, 18.3034,  9.607 , 27.7747, 10.1191,
       28.4194, 20.9575, 22.0555, 22.0357, 12.2064, 17.8279, 28.8608,
       21.1291, 17.2569, 25.0831, 18.1969, 20.5849, 13.8951, 12.0658,
        9.2057, 11.0667, 18.1438, 29.8061, 20.8595, 12.9242, 22.6849,
        9.5824, 15.354 , 27.968 , 20.7667, 17.7127, 14.9528,  6.7076,
       19.9403, 14.7396,  9.095 , 18.3906, 10.1553,  5.1704, 24.72  ,
       14.8958,  7.6076,  9.6294, 19.3497, 28.8784,  7.2905, 25.0898,
       13.2301, 27.9575, 21.7023, 19.9461, 16.4322, 24.0799, 21.6742,
       17.0318, 18.9981, 16.7148, 30.7132, 21.9007, 16.3293,  8.6074,
       26.2682, 13.3013,  7.5146, 13.7114, 14.9001, 11.2123,  8.3057,
       16.2472,  9.4004, 20.3773, 17.6887, 21.8433, 17.0272, 12.8802,
       30.5342,  9.8275,  6.6234,  4.0342, 17.4638,  8.3662,  8.9648,
       17.7394, 15.9744,  7.0548, 13.4563, 29.8096, 16.4708, 25.299 ,
       15.8824, 13.4489, 10.2387, 17.708 , 12.9453,  5.1694,  8.4355,
       15.8202, 15.6279, 30.351 , 27.1055, 26.6143, 18.2887,  5.5674,
       22.821 , 29.4036, 25.1616, 17.2319, 28.3602, 11.0392, 13.5516,
        7.9998,  6.509 , 31.9764,  5.782 ,  8.3133, 25.4813])

## Datos faltantes

In [276]:
bancarios = np.array([1.85, 2.13, np.nan, 4.25, 5.08])
bancarios

array([1.85, 2.13,  nan, 4.25, 5.08])

In [277]:
np.isnan(bancarios)

array([False, False,  True, False, False])

In [278]:
np.mean(bancarios)

np.float64(nan)

In [279]:
# Funciones para arreglos con vacíos
np.nanmean(bancarios)

np.float64(3.3275)

In [280]:
# Sustituir por valores válidos
bancarios_validos = np.where(
    np.isnan(bancarios),
    np.nanmean(bancarios),
    bancarios
)

bancarios_validos

array([1.85  , 2.13  , 3.3275, 4.25  , 5.08  ])

In [281]:
# Eliminar elementos no válidos
bancarios_validos = bancarios[~np.isnan(bancarios)]
bancarios_validos

array([1.85, 2.13, 4.25, 5.08])

## Exportación e Importación de Datos

In [282]:
pagos = np.genfromtxt('Pagos.csv', delimiter=',')
pagos

array([[        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       [        nan, 42682691.  ,      331.  , ...,        0.  ,
             229.98,        0.  ],
       [        nan, 40119499.  ,      305.  , ...,        0.  ,
             199.99,        0.  ],
       ...,
       [        nan, 43189845.  ,       69.  , ...,        0.  ,
             252.64,        0.  ],
       [        nan, 20100839.  ,       79.  , ...,        0.  ,
             301.97,        0.  ],
       [        nan, 40010570.  ,       62.  , ...,        0.  ,
             499.92,        0.  ]])

In [283]:
pagos = np.genfromtxt(
    'Pagos.csv',
    delimiter=',',
    filling_values=0,
    skip_header=1,
    dtype = int
)
pagos

array([[       0, 42682691,      331, ...,        0,        0,        0],
       [       0, 40119499,      305, ...,        0,        0,        0],
       [       0, 42317124,      375, ...,        0,        0,        0],
       ...,
       [       0, 43189845,       69, ...,        0,        0,        0],
       [       0, 20100839,       79, ...,        0,        0,        0],
       [       0, 40010570,       62, ...,        0,        0,        0]])

In [284]:
# Eliminar columnas con puros ceros
pagos_numericos = pagos[:, ~np.all(pagos == 0, axis=0)]
pagos_numericos

array([[   42682691,         331,        6735,           1, 90935236916],
       [   40119499,         305,       11427,           1, 90968113434],
       [   42317124,         375,        8774,           1, 90911269609],
       ...,
       [   43189845,          69,        3760,           2, 90944298234],
       [   20100839,          79,        3131,           1, 90995457601],
       [   40010570,          62,         594,           1, 90960219630]])

In [285]:
# Exportar
np.savetxt(
    'pagos_numericos.csv',
    pagos_numericos,
    delimiter=';',
    fmt='%d'
)

## Numpy + Pandas

In [286]:
df_nano = df_sales[['Unit price', 'Quantity', 'Tax 5%', 'Total', 'cogs', 'gross margin percentage', 'gross income', 'Rating']].head(5)

df_nano

,Unit price,Quantity,Tax 5%,Total,cogs,gross margin percentage,gross income,Rating
0,74.69,7,26.1415,548.9715,522.83,4.761905,26.1415,9.1
1,15.28,5,3.8200,80.2200,76.40,4.761905,3.8200,9.6
2,46.33,7,16.2155,340.5255,324.31,4.761905,16.2155,7.4
3,58.22,8,23.2880,489.0480,465.76,4.761905,23.2880,8.4
4,86.31,7,30.2085,634.3785,604.17,4.761905,30.2085,5.3

In [287]:
# De Dataframe a Array
sales_primary = df_nano[['Unit price', 'Quantity', 'Tax 5%', 'Total']].values
sales_primary

array([[ 74.69  ,   7.    ,  26.1415, 548.9715],
       [ 15.28  ,   5.    ,   3.82  ,  80.22  ],
       [ 46.33  ,   7.    ,  16.2155, 340.5255],
       [ 58.22  ,   8.    ,  23.288 , 489.048 ],
       [ 86.31  ,   7.    ,  30.2085, 634.3785]])

In [288]:
sales_secondary = df_nano[['cogs', 'gross margin percentage', 'gross income', 'Rating']].to_numpy()
sales_secondary

array([[522.83  ,   4.7619,  26.1415,   9.1   ],
       [ 76.4   ,   4.7619,   3.82  ,   9.6   ],
       [324.31  ,   4.7619,  16.2155,   7.4   ],
       [465.76  ,   4.7619,  23.288 ,   8.4   ],
       [604.17  ,   4.7619,  30.2085,   5.3   ]])

In [289]:
# Comparten funciones
np.sqrt(df_sales['cogs'].head(3))

0    22.865476
1     8.740709
2    18.008609
Name: cogs, dtype: float64

In [290]:
np.max(df_sales['gross income'].head(3))

26.1415

In [291]:
# De Array a Dataframe
df_filtrado = pd.DataFrame(sales_primary, columns=['precio_unitario', 'cantidad', 'impuesto', 'total'])
df_filtrado

   precio_unitario  cantidad  impuesto     total
0            74.69       7.0   26.1415  548.9715
1            15.28       5.0    3.8200   80.2200
2            46.33       7.0   16.2155  340.5255
3            58.22       8.0   23.2880  489.0480
4            86.31       7.0   30.2085  634.3785

## Proyecto

In [292]:
sales_primary = sales_primary.T
sales_primary

array([[ 74.69  ,  15.28  ,  46.33  ,  58.22  ,  86.31  ],
       [  7.    ,   5.    ,   7.    ,   8.    ,   7.    ],
       [ 26.1415,   3.82  ,  16.2155,  23.288 ,  30.2085],
       [548.9715,  80.22  , 340.5255, 489.048 , 634.3785]])

In [293]:
sales_primary = np.vstack((sales_primary, sales_primary[0] * sales_primary[1]))
sales_primary

array([[ 74.69  ,  15.28  ,  46.33  ,  58.22  ,  86.31  ],
       [  7.    ,   5.    ,   7.    ,   8.    ,   7.    ],
       [ 26.1415,   3.82  ,  16.2155,  23.288 ,  30.2085],
       [548.9715,  80.22  , 340.5255, 489.048 , 634.3785],
       [522.83  ,  76.4   , 324.31  , 465.76  , 604.17  ]])

In [294]:
sales_primary = np.vstack((sales_primary, sales_primary[4] * 0.05))
sales_primary

array([[ 74.69  ,  15.28  ,  46.33  ,  58.22  ,  86.31  ],
       [  7.    ,   5.    ,   7.    ,   8.    ,   7.    ],
       [ 26.1415,   3.82  ,  16.2155,  23.288 ,  30.2085],
       [548.9715,  80.22  , 340.5255, 489.048 , 634.3785],
       [522.83  ,  76.4   , 324.31  , 465.76  , 604.17  ],
       [ 26.1415,   3.82  ,  16.2155,  23.288 ,  30.2085]])

In [295]:
sales_primary = np.vstack((sales_primary, sales_primary[4] + sales_primary[5]))
sales_primary

array([[ 74.69  ,  15.28  ,  46.33  ,  58.22  ,  86.31  ],
       [  7.    ,   5.    ,   7.    ,   8.    ,   7.    ],
       [ 26.1415,   3.82  ,  16.2155,  23.288 ,  30.2085],
       [548.9715,  80.22  , 340.5255, 489.048 , 634.3785],
       [522.83  ,  76.4   , 324.31  , 465.76  , 604.17  ],
       [ 26.1415,   3.82  ,  16.2155,  23.288 ,  30.2085],
       [548.9715,  80.22  , 340.5255, 489.048 , 634.3785]])